"""
generate_sql.py
reads all 100 lesson JSON files from lessons/ and generates a SQL migration
that replaces the lessons + sentences tables with the 100-day curriculum.

Run: python generate_sql.py
Output: supabase-lessons.sql
"""

import json
import os

LESSONS_DIR = os.path.join(os.path.dirname(__file__), "lessons")
SQL_OUT = os.path.join(os.path.dirname(__file__), "supabase-lessons.sql")

def esc(s):
    """Escape a string for SQL single-quoted literals."""
    if s is None:
        return "NULL"
    return "'" + str(s).replace("'", "''") + "'"

lines = []
lines.append("-- =====================================================")
lines.append("-- Mirifer: 100-Day Curriculum Migration")
lines.append("-- Generated by generate_sql.py")
lines.append("-- Run this in the Supabase SQL editor.")
lines.append("-- WARNING: Deletes all existing lessons and sentences!")
lines.append("-- =====================================================")
lines.append("")
lines.append("BEGIN;")
lines.append("")
lines.append("-- 0. Update constraints if necessary")
lines.append("ALTER TABLE lessons DROP CONSTRAINT IF EXISTS lessons_difficulty_check;")
lines.append("ALTER TABLE lessons ADD CONSTRAINT lessons_difficulty_check CHECK (difficulty IN ('A1', 'A1+', 'A2', 'A2+', 'B1', 'B1+', 'B2', 'B2+', 'C1', 'C2'));")
lines.append("")
lines.append("-- Ensure sentences table has day and difficulty columns")
lines.append("ALTER TABLE sentences ADD COLUMN IF NOT EXISTS day INTEGER;")
lines.append("ALTER TABLE sentences ADD COLUMN IF NOT EXISTS difficulty TEXT;")
lines.append("ALTER TABLE sentences DROP CONSTRAINT IF EXISTS sentences_difficulty_check;")
lines.append("ALTER TABLE sentences ADD CONSTRAINT sentences_difficulty_check CHECK (difficulty IN ('A1', 'A1+', 'A2', 'A2+', 'B1', 'B1+', 'B2', 'B2+', 'C1', 'C2'));")
lines.append("")
lines.append("-- 1. Clear existing data (sentences first due to FK)")
lines.append("DELETE FROM sentences;")
lines.append("DELETE FROM lessons;")
lines.append("")
lines.append("-- 2. Reset sequences (optional, keeps IDs clean)")
lines.append("-- ALTER SEQUENCE lessons_id_seq RESTART WITH 1;")
lines.append("-- ALTER SEQUENCE sentences_id_seq RESTART WITH 1;")
lines.append("")
lines.append("-- 3. Insert lessons")

for day in range(1, 101):
    path = os.path.join(LESSONS_DIR, f"day-{day}.json")
    if not os.path.exists(path):
        print(f"WARNING: day-{day}.json missing, skipping")
        continue
    with open(path, encoding="utf-8") as f:
        data = json.load(f)

    title = f"{day}: {data.get('title', f'Day {day}')}"
    # Remove redundant day number if it was already prepended in JSON
    if title.startswith(f"{day}: {day}:"):
        title = title.replace(f"{day}: {day}:", f"{day}:", 1)
    title_fa = data.get("titleFa", "")
    
    # Simple mapping for groups in 90 day curriculum
    if day <= 15:
        group = "basics"
    elif day <= 45:
        group = "survival"
    elif day <= 75:
        group = "scenarios"
    else:
        group = "advanced"

    description      = data.get("description", None)
    description_fa   = data.get("descriptionFa", None)
    grammar_focus    = data.get("grammarFocus", None)
    grammar_focus_fa = data.get("grammarFocusFa", None)
    difficulty       = data.get("difficulty", None)

    lines.append(
        f"INSERT INTO lessons (day, title, title_fa, \"group\", sort_order, "
        f"description, description_fa, grammar_focus, grammar_focus_fa, difficulty) "
        f"VALUES ({day}, {esc(title)}, {esc(title_fa)}, {esc(group)}, {day}, "
        f"{esc(description)}, {esc(description_fa)}, {esc(grammar_focus)}, "
        f"{esc(grammar_focus_fa)}, {esc(difficulty)});"
    )

lines.append("")
lines.append("-- 4. Insert sentences (using lesson day to find lesson_id)")

for day in range(1, 101):
    path = os.path.join(LESSONS_DIR, f"day-{day}.json")
    if not os.path.exists(path):
        continue
    with open(path, encoding="utf-8") as f:
        data = json.load(f)

    sentences = data.get("sentences", [])
    lines.append(f"-- Day {day}: {data.get('title', '')}")
    for i, s in enumerate(sentences):
        role = s.get("role", "sent")
        audio_text = s.get("audioText") if role == "received" else None
        target_text = s.get("targetText") if role == "sent" else None
        translation = s.get("translation", "")
        translation_fa = s.get("translationFa", "")

        hint    = s.get("hint", None)
        hint_fa = s.get("hintFa", None)
        s_day   = s.get("day", day)
        s_diff  = s.get("difficulty", data.get("difficulty", "A1"))

        lines.append(
            f"INSERT INTO sentences (lesson_id, day, difficulty, sentence_order, role, audio_text, target_text, translation, translation_fa, hint, hint_fa) "
            f"SELECT id, {s_day}, {esc(s_diff)}, {i}, {esc(role)}, {esc(audio_text)}, {esc(target_text)}, "
            f"{esc(translation)}, {esc(translation_fa)}, {esc(hint)}, {esc(hint_fa)} FROM lessons WHERE day = {day};"
        )

lines.append("")
lines.append("COMMIT;")
lines.append("")
lines.append("-- Verify counts:")
lines.append("-- SELECT COUNT(*) FROM lessons;   -- should be 100")
lines.append("-- SELECT COUNT(*) FROM sentences; -- should be ~1000")

sql = "\n".join(lines)
with open(SQL_OUT, "w", encoding="utf-8") as f:
    f.write(sql)

print(f"SQL written to: {SQL_OUT}")
print(f"Total lines: {len(lines)}")

