-- ============================================================
-- MISIRO: Glossary Additions (~170 new entries)
-- Run this in Supabase SQL Editor AFTER the existing glossary
-- INSERT ON CONFLICT (word) DO UPDATE to be safe on re-runs.
-- ============================================================

INSERT INTO public.glossary (word, en, fa) VALUES
-- ── Greetings & Basics ──────────────────────────────────────
('hallo', 'hello', 'سلام'),
('guten morgen', 'good morning', 'صبح بخیر'),
('guten tag', 'good day', 'روز بخیر'),
('guten abend', 'good evening', 'شب بخیر'),
('auf wiedersehen', 'goodbye (formal)', 'خداحافظ (رسمی)'),
('tschüss', 'bye (informal)', 'خداحافظ (غیررسمی)'),
('bis bald', 'see you soon', 'به زودی می‌بینمتون'),
('bitte', 'please / you''re welcome', 'لطفاً / خواهش می‌کنم'),
('danke', 'thank you', 'ممنون'),
('vielen dank', 'many thanks', 'خیلی ممنون'),
('entschuldigung', 'excuse me / sorry', 'ببخشید'),
('es tut mir leid', 'I am sorry', 'متأسفم'),
('kein problem', 'no problem', 'مشکلی نیست'),
('natürlich', 'of course', 'البته'),
('gerne', 'gladly / with pleasure', 'خوشحال می‌شم / با کمال میل'),
('ja', 'yes', 'بله'),
('nein', 'no', 'نه'),
-- ── People & Introduction ───────────────────────────────────
('ich', 'I', 'من'),
('sie', 'you (formal) / she / they', 'شما (رسمی) / او / آنها'),
('heißen', 'to be called', 'نام داشتن'),
('arbeiten', 'to work', 'کار کردن'),
('wohnen', 'to live / to reside', 'زندگی کردن / ساکن بودن'),
('lernen', 'to learn', 'یاد گرفتن'),
('sprechen', 'to speak', 'صحبت کردن'),
('verstehen', 'to understand', 'فهمیدن'),
('fragen', 'to ask', 'پرسیدن'),
('antworten', 'to answer', 'جواب دادن'),
('zeigen', 'to show', 'نشان دادن'),
-- ── Numbers & Time ──────────────────────────────────────────
('die uhrzeit', 'the time (clock time)', 'ساعت'),
('die minute', 'the minute', 'دقیقه'),
('die stunde', 'the hour', 'ساعت (مدت)'),
('der tag', 'the day', 'روز'),
('die woche', 'the week', 'هفته'),
('der monat', 'the month', 'ماه'),
('das jahr', 'the year', 'سال'),
('heute', 'today', 'امروز'),
('morgen', 'tomorrow', 'فردا'),
('gestern', 'yesterday', 'دیروز'),
('jetzt', 'now', 'الان'),
('früh', 'early', 'زود'),
('spät', 'late', 'دیر'),
-- ── Family ──────────────────────────────────────────────────
('die mutter', 'the mother', 'مادر'),
('der vater', 'the father', 'پدر'),
('die schwester', 'the sister', 'خواهر'),
('der bruder', 'the brother', 'برادر'),
('die tochter', 'the daughter', 'دختر'),
('der sohn', 'the son', 'پسر'),
('die eltern', 'the parents', 'والدین'),
('verheiratet', 'married', 'متأهل'),
('ledig', 'single', 'مجرد'),
-- ── Transport & Directions ──────────────────────────────────
('der zug', 'the train', 'قطار'),
('der bus', 'the bus', 'اتوبوس'),
('das taxi', 'the taxi', 'تاکسی'),
('das flugzeug', 'the airplane', 'هواپیما'),
('der flughafen', 'the airport', 'فرودگاه'),
('der bahnhof', 'the train station', 'ایستگاه قطار'),
('die haltestelle', 'the bus stop', 'ایستگاه اتوبوس'),
('die fahrkarte', 'the ticket', 'بلیت'),
('geradeaus', 'straight ahead', 'مستقیم'),
('links', 'left', 'چپ'),
('rechts', 'right', 'راست'),
('die kreuzung', 'the intersection', 'تقاطع'),
('die straße', 'the street', 'خیابان'),
('der weg', 'the way / path', 'مسیر'),
('neben', 'next to', 'کنار'),
('gegenüber', 'opposite', 'روبرو'),
('weit', 'far', 'دور'),
('nah', 'near', 'نزدیک'),
('umsteigen', 'to transfer / change (transport)', 'تعویض وسیله نقلیه'),
-- ── Weather ─────────────────────────────────────────────────
('das wetter', 'the weather', 'آب‌وهوا'),
('die sonne', 'the sun', 'خورشید'),
('der regen', 'the rain', 'باران'),
('der schnee', 'the snow', 'برف'),
('warm', 'warm', 'گرم'),
('kalt', 'cold', 'سرد'),
('die wolke', 'the cloud', 'ابر'),
('der wind', 'the wind', 'باد'),
-- ── Food & Drink ────────────────────────────────────────────
('das frühstück', 'breakfast', 'صبحانه'),
('das mittagessen', 'lunch', 'ناهار'),
('das abendessen', 'dinner', 'شام'),
('das brot', 'the bread', 'نان'),
('der kaffee', 'the coffee', 'قهوه'),
('der tee', 'the tea', 'چای'),
('das wasser', 'the water', 'آب'),
('die milch', 'the milk', 'شیر'),
('der zucker', 'the sugar', 'شکر'),
('das fleisch', 'the meat', 'گوشت'),
('das gemüse', 'the vegetables', 'سبزیجات'),
('das obst', 'the fruit', 'میوه'),
('die speisekarte', 'the menu', 'منو'),
('bestellen', 'to order', 'سفارش دادن'),
('bezahlen', 'to pay', 'پرداخت کردن'),
('die rechnung', 'the bill / invoice', 'صورت‌حساب'),
('lecker', 'delicious', 'خوشمزه'),
('hungrig', 'hungry', 'گرسنه'),
('durstig', 'thirsty', 'تشنه'),
-- ── Shopping & Money ────────────────────────────────────────
('kaufen', 'to buy', 'خریدن'),
('verkaufen', 'to sell', 'فروختن'),
('der preis', 'the price', 'قیمت'),
('teuer', 'expensive', 'گران'),
('günstig', 'affordable / cheap', 'ارزان'),
('das geld', 'the money', 'پول'),
('die kasse', 'the checkout / cash register', 'صندوق'),
('die kreditkarte', 'the credit card', 'کارت اعتباری'),
('bar', 'cash', 'نقد'),
('das geschäft', 'the shop / business', 'مغازه'),
('die größe', 'the size', 'سایز'),
('anprobieren', 'to try on', 'امتحان کردن (لباس)'),
-- ── Health ──────────────────────────────────────────────────
('krank', 'sick / ill', 'مریض'),
('gesund', 'healthy', 'سالم'),
('der arzt', 'the doctor (male)', 'دکتر (مرد)'),
('die ärztin', 'the doctor (female)', 'دکتر (زن)'),
('das krankenhaus', 'the hospital', 'بیمارستان'),
('die apotheke', 'the pharmacy', 'داروخانه'),
('das medikament', 'the medicine', 'دارو'),
('der schmerz', 'the pain', 'درد'),
('wehtun', 'to hurt', 'درد کردن'),
('das fieber', 'the fever', 'تب'),
('der husten', 'the cough', 'سرفه'),
('die erkältung', 'the cold (illness)', 'سرماخوردگی'),
-- ── Work & Office ───────────────────────────────────────────
('die arbeit', 'the work / job', 'کار'),
('das büro', 'the office', 'دفتر'),
('der kollege', 'the colleague (male)', 'همکار (مرد)'),
('die kollegin', 'the colleague (female)', 'همکار (زن)'),
('die besprechung', 'the meeting', 'جلسه'),
('die aufgabe', 'the task', 'وظیفه'),
('schicken', 'to send', 'فرستادن'),
('erledigen', 'to complete / handle', 'انجام دادن'),
('das telefon', 'the telephone', 'تلفن'),
('die e-mail', 'the email', 'ایمیل'),
('der termin', 'the appointment', 'قرار ملاقات'),
('verschieben', 'to postpone / reschedule', 'به تعویق انداختن'),
-- ── Home & Living ───────────────────────────────────────────
('die wohnung', 'the apartment', 'آپارتمان'),
('das haus', 'the house', 'خانه'),
('das zimmer', 'the room', 'اتاق'),
('das schlafzimmer', 'the bedroom', 'اتاق خواب'),
('das wohnzimmer', 'the living room', 'اتاق نشیمن'),
('die küche', 'the kitchen', 'آشپزخانه'),
('das badezimmer', 'the bathroom', 'حمام'),
('die miete', 'the rent', 'اجاره'),
('die nebenkosten', 'the utilities', 'هزینه‌های جانبی'),
('der schlüssel', 'the key', 'کلید'),
-- ── Adjectives & Descriptions ───────────────────────────────
('groß', 'big / tall', 'بزرگ / بلند'),
('klein', 'small / short', 'کوچک / کوتاه'),
('alt', 'old', 'قدیمی / مسن'),
('neu', 'new', 'جدید'),
('schön', 'beautiful / nice', 'زیبا'),
('schlecht', 'bad', 'بد'),
('schwierig', 'difficult', 'سخت'),
('einfach', 'simple / easy', 'ساده / آسان'),
('schnell', 'fast', 'سریع'),
('langsam', 'slow', 'کند'),
('müde', 'tired', 'خسته'),
('wichtig', 'important', 'مهم'),
-- ── Common Verbs ────────────────────────────────────────────
('helfen', 'to help', 'کمک کردن'),
('brauchen', 'to need', 'نیاز داشتن'),
('haben', 'to have', 'داشتن'),
('sein', 'to be', 'بودن'),
('gehen', 'to go', 'رفتن'),
('kommen', 'to come', 'آمدن'),
('machen', 'to do / make', 'کردن / ساختن'),
('sehen', 'to see', 'دیدن'),
('hören', 'to hear', 'شنیدن'),
('wissen', 'to know (a fact)', 'دانستن'),
('kennen', 'to know (a person/place)', 'شناختن'),
('denken', 'to think', 'فکر کردن'),
('finden', 'to find / think', 'پیدا کردن / فکر کردن'),
('nehmen', 'to take', 'گرفتن / بردن'),
('geben', 'to give', 'دادن'),
('möchten', 'would like', 'می‌خواهم'),
('müssen', 'must / have to', 'باید'),
('können', 'can / to be able to', 'توانستن'),
('dürfen', 'may / to be allowed to', 'اجازه داشتن'),
('wollen', 'to want', 'خواستن'),
-- ── Emergency & Important Phrases ───────────────────────────
('hilfe', 'help!', 'کمک!'),
('vorsicht', 'careful! / watch out!', 'مراقب باش!'),
('die polizei', 'the police', 'پلیس'),
('die feuerwehr', 'the fire brigade', 'آتش‌نشانی'),
('der notfall', 'the emergency', 'اورژانس / بحران'),
('verloren', 'lost', 'گم شده'),
('gestohlen', 'stolen', 'دزدیده شده'),
('der pass', 'the passport', 'پاسپورت')
ON CONFLICT (word) DO UPDATE
  SET en = EXCLUDED.en,
      fa = EXCLUDED.fa,
      updated_at = now();
