-- First-release learner insights. Run once in the Supabase SQL editor before deploying.
-- Safe to run again; legacy events remain unchanged and are not treated as complete visits.
BEGIN;
CREATE TABLE IF NOT EXISTS public.events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  event_name TEXT NOT NULL, day INTEGER, metadata JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS event_id UUID;
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS session_id UUID;
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS attempt_id UUID;
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS occurred_at TIMESTAMPTZ;
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS schema_version INTEGER;
CREATE UNIQUE INDEX IF NOT EXISTS events_event_id_unique ON public.events(event_id);
CREATE INDEX IF NOT EXISTS events_schema_time ON public.events(schema_version, created_at);
CREATE INDEX IF NOT EXISTS events_user_visit ON public.events(user_id, session_id);
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can insert own events" ON public.events;
CREATE POLICY "Users can insert own events" ON public.events FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can view own events" ON public.events;
CREATE POLICY "Users can view own events" ON public.events FOR SELECT TO authenticated USING (auth.uid() = user_id);
GRANT SELECT, INSERT ON public.events TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.events_id_seq TO authenticated;

CREATE TABLE IF NOT EXISTS public.analytics_settings (
  id BOOLEAN PRIMARY KEY DEFAULT true CHECK (id),
  schema_version INTEGER NOT NULL DEFAULT 2,
  installed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO public.analytics_settings(id) VALUES (true) ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS public.analytics_exclusions (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE public.analytics_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.analytics_exclusions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.analytics_settings, public.analytics_exclusions FROM anon, authenticated;
GRANT ALL ON public.analytics_settings, public.analytics_exclusions TO service_role;
GRANT ALL ON public.events TO service_role;

-- Admin reports rely on this flag. An ordinary profile edit must never grant it.
CREATE OR REPLACE FUNCTION public.protect_profile_admin_flag() RETURNS trigger
LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  IF current_user IN ('anon', 'authenticated') THEN
    IF TG_OP = 'INSERT' THEN
      IF NEW.is_admin IS TRUE THEN RAISE EXCEPTION 'Admin role cannot be self-assigned'; END IF;
    ELSIF NEW.is_admin IS DISTINCT FROM OLD.is_admin THEN
      RAISE EXCEPTION 'Admin role cannot be changed by a learner';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS protect_profile_admin_flag ON public.user_profiles;
CREATE TRIGGER protect_profile_admin_flag BEFORE INSERT OR UPDATE ON public.user_profiles
FOR EACH ROW EXECUTE FUNCTION public.protect_profile_admin_flag();
COMMIT;
