-- ============================================================================
--  MIRIFER — Days 101-120: the final twenty
--
--  The landing page has always advertised 120 days and the course stopped at
--  100. This closes that gap.
--
--  These are the last lessons in the path, so they are deliberately the
--  hardest: 13-15 sentences each (the B1 band in curriculum.ts), longer turns,
--  and grammar that has not appeared before — Konjunktiv II across whole
--  arguments, Passiv, relative clauses, indirect speech, Genitiv, and the
--  two-part connectors that make German sound like an adult wrote it.
--
--  The scenes are chosen for the audience rather than for a textbook: a job
--  interview, the Bürgeramt, a rental contract, a salary negotiation, a
--  disagreement with a neighbour. These are the situations that decide how
--  someone's life in Germany actually goes.
--
--  Run once in the Supabase SQL editor. Safe to re-run: each day is deleted
--  before it is re-inserted, and sentences cascade.
-- ============================================================================

BEGIN;

-- Idempotent: drop these twenty days first so a re-run replaces rather than
-- duplicates. ON DELETE CASCADE removes their sentences with them.
DELETE FROM public.lessons WHERE day BETWEEN 101 AND 120;

-- ── Lesson rows ─────────────────────────────────────────────────────────────
INSERT INTO lessons (day, title, title_fa, "group", sort_order, grammar_focus, grammar_focus_fa, difficulty) VALUES
(101, 'Day 101: The Job Interview', 'روز ۱۰۱: مصاحبهٔ شغلی', 'advanced', 101, 'Perfekt for experience; weil/da for reasons; formal Sie register', 'گذشتهٔ نقلی برای سابقه؛ weil/da برای دلیل؛ لحن رسمی Sie', 'B1+'),
(102, 'Day 102: Reading the Rental Contract', 'روز ۱۰۲: خواندن قرارداد اجاره', 'advanced', 102, 'Passiv (wird … vermietet); Genitiv; conditional clauses with falls', 'مجهول (wird … vermietet)؛ اضافه؛ شرط با falls', 'B1+'),
(103, 'Day 103: At the Bürgeramt', 'روز ۱۰۳: در ادارهٔ ثبت احوال', 'advanced', 103, 'Indirect questions (ob, wo, wann); nominalised verbs; officialese', 'پرسش غیرمستقیم (ob, wo, wann)؛ اسم‌شدن فعل؛ زبان اداری', 'B1+'),
(104, 'Day 104: Opening a Bank Account', 'روز ۱۰۴: باز کردن حساب بانکی', 'advanced', 104, 'Relative clauses with prepositions; um … zu; comparatives', 'جملهٔ موصولی با حرف اضافه؛ um … zu؛ صفت تفضیلی', 'B1+'),
(105, 'Day 105: A Problem With the Neighbour', 'روز ۱۰۵: مشکل با همسایه', 'advanced', 105, 'Konjunktiv II for politeness; obwohl; softening a complaint', 'التزامی دوم برای ادب؛ obwohl؛ نرم کردن شکایت', 'B1+');

-- ── Day 101: The Job Interview ──────────────────────────────────────────────
INSERT INTO sentences (lesson_id, sentence_order, role, audio_text, target_text, translation, translation_fa) VALUES
((SELECT id FROM lessons WHERE day = 101), 1, 'received', 'Guten Tag, schön dass Sie da sind. Nehmen Sie bitte Platz.', NULL, 'Good afternoon, glad you could come. Please take a seat.', 'روز بخیر، خوشحالم که آمدید. لطفاً بفرمایید بنشینید.'),
((SELECT id FROM lessons WHERE day = 101), 2, 'sent', NULL, 'Vielen Dank für die Einladung. Ich freue mich auf das Gespräch.', 'Thank you for the invitation. I am looking forward to the conversation.', 'از دعوتتان ممنونم. مشتاق این گفت‌وگو هستم.'),
((SELECT id FROM lessons WHERE day = 101), 3, 'received', 'Erzählen Sie uns bitte kurz etwas über Ihren beruflichen Werdegang.', NULL, 'Please tell us briefly about your professional background.', 'لطفاً کوتاه دربارهٔ سابقهٔ کاری‌تان بگویید.'),
((SELECT id FROM lessons WHERE day = 101), 4, 'sent', NULL, 'Ich habe fünf Jahre als Ingenieur gearbeitet, zuletzt in einem mittelständischen Unternehmen.', 'I worked as an engineer for five years, most recently at a mid-sized company.', 'پنج سال به عنوان مهندس کار کرده‌ام، آخرین بار در یک شرکت متوسط.'),
((SELECT id FROM lessons WHERE day = 101), 5, 'received', 'Und warum möchten Sie sich gerade bei uns verändern?', NULL, 'And why do you want to make a change to our company in particular?', 'و چرا می‌خواهید دقیقاً به شرکت ما بیایید؟'),
((SELECT id FROM lessons WHERE day = 101), 6, 'sent', NULL, 'Weil Ihr Unternehmen für nachhaltige Projekte bekannt ist, und daran möchte ich mitarbeiten.', 'Because your company is known for sustainable projects, and I would like to be part of that.', 'چون شرکت شما به پروژه‌های پایدار شناخته می‌شود و می‌خواهم در آن سهیم باشم.'),
((SELECT id FROM lessons WHERE day = 101), 7, 'received', 'Was würden Sie als Ihre größte Schwäche bezeichnen?', NULL, 'What would you describe as your greatest weakness?', 'بزرگ‌ترین ضعفتان را چه می‌دانید؟'),
((SELECT id FROM lessons WHERE day = 101), 8, 'sent', NULL, 'Ich neige dazu, zu lange an Details zu arbeiten. Daran arbeite ich bewusst.', 'I tend to work on details for too long. I am consciously working on that.', 'گرایش دارم بیش از حد روی جزئیات وقت بگذارم. آگاهانه رویش کار می‌کنم.'),
((SELECT id FROM lessons WHERE day = 101), 9, 'received', 'Wie gehen Sie damit um, wenn ein Projekt scheitert?', NULL, 'How do you deal with it when a project fails?', 'وقتی پروژه‌ای شکست می‌خورد چطور با آن کنار می‌آیید؟'),
((SELECT id FROM lessons WHERE day = 101), 10, 'sent', NULL, 'Ich analysiere zuerst die Ursachen, bevor ich Schuld verteile. Das hat mir schon oft geholfen.', 'I analyse the causes first, before assigning blame. That has often helped me.', 'اول علت‌ها را بررسی می‌کنم، پیش از آنکه کسی را مقصر بدانم. این بارها کمکم کرده.'),
((SELECT id FROM lessons WHERE day = 101), 11, 'received', 'Haben Sie Fragen an uns?', NULL, 'Do you have any questions for us?', 'سؤالی از ما دارید؟'),
((SELECT id FROM lessons WHERE day = 101), 12, 'sent', NULL, 'Ja. Wie sieht die Einarbeitung in den ersten Monaten aus?', 'Yes. What does the onboarding look like in the first months?', 'بله. آموزش اولیه در ماه‌های نخست چگونه است؟'),
((SELECT id FROM lessons WHERE day = 101), 13, 'received', 'Sie bekommen eine feste Ansprechpartnerin und einen Einarbeitungsplan für drei Monate.', NULL, 'You will get a dedicated contact person and a three-month onboarding plan.', 'یک نفر مشخص راهنمای شماست و یک برنامهٔ سه‌ماههٔ آموزش دارید.'),
((SELECT id FROM lessons WHERE day = 101), 14, 'sent', NULL, 'Das klingt sehr gut. Wann darf ich mit einer Rückmeldung rechnen?', 'That sounds very good. When can I expect to hear back?', 'خیلی خوب به نظر می‌رسد. کی می‌توانم منتظر پاسخ باشم؟'),
((SELECT id FROM lessons WHERE day = 101), 15, 'received', 'Wir melden uns spätestens bis Ende nächster Woche bei Ihnen.', NULL, 'We will get back to you by the end of next week at the latest.', 'حداکثر تا پایان هفتهٔ آینده با شما تماس می‌گیریم.');

-- ── Day 102: Reading the Rental Contract ────────────────────────────────────
INSERT INTO sentences (lesson_id, sentence_order, role, audio_text, target_text, translation, translation_fa) VALUES
((SELECT id FROM lessons WHERE day = 102), 1, 'received', 'Hier ist der Mietvertrag. Bitte lesen Sie ihn in Ruhe durch.', NULL, 'Here is the rental contract. Please read through it calmly.', 'این قرارداد اجاره است. لطفاً با آرامش بخوانیدش.'),
((SELECT id FROM lessons WHERE day = 102), 2, 'sent', NULL, 'Darf ich fragen, was genau in der Nebenkostenabrechnung enthalten ist?', 'May I ask what exactly is included in the utilities statement?', 'می‌توانم بپرسم دقیقاً چه چیزی در صورتحساب هزینه‌های جانبی هست؟'),
((SELECT id FROM lessons WHERE day = 102), 3, 'received', 'Heizung, Wasser und Müllabfuhr sind enthalten. Strom müssen Sie selbst anmelden.', NULL, 'Heating, water and rubbish collection are included. You have to register electricity yourself.', 'گرمایش، آب و جمع‌آوری زباله شامل است. برق را باید خودتان ثبت کنید.'),
((SELECT id FROM lessons WHERE day = 102), 4, 'sent', NULL, 'Und die Kaution? Wird sie am Ende vollständig zurückgezahlt?', 'And the deposit? Is it paid back in full at the end?', 'و ودیعه؟ آیا در پایان کامل پس داده می‌شود؟'),
((SELECT id FROM lessons WHERE day = 102), 5, 'received', 'Die Kaution wird zurückgezahlt, sofern die Wohnung in ordentlichem Zustand übergeben wird.', NULL, 'The deposit is refunded provided the flat is handed over in proper condition.', 'ودیعه پس داده می‌شود، به شرط آنکه خانه در وضعیت مناسب تحویل شود.'),
((SELECT id FROM lessons WHERE day = 102), 6, 'sent', NULL, 'Falls ich früher ausziehen muss, wie lang ist die Kündigungsfrist?', 'If I have to move out earlier, how long is the notice period?', 'اگر مجبور شوم زودتر بروم، مهلت فسخ چقدر است؟'),
((SELECT id FROM lessons WHERE day = 102), 7, 'received', 'Die Frist beträgt drei Monate zum Monatsende. Das steht in Paragraf sieben.', NULL, 'The period is three months to the end of the month. That is in paragraph seven.', 'مهلت سه ماه تا پایان ماه است. در بند هفت آمده.'),
((SELECT id FROM lessons WHERE day = 102), 8, 'sent', NULL, 'Ich habe gelesen, dass Haustiere nur mit Genehmigung des Vermieters erlaubt sind.', 'I read that pets are only allowed with the landlord''s permission.', 'خواندم که نگهداری حیوان خانگی فقط با اجازهٔ مالک مجاز است.'),
((SELECT id FROM lessons WHERE day = 102), 9, 'received', 'Das stimmt. Bei einer Katze ist das aber normalerweise kein Problem.', NULL, 'That is right. With a cat it is usually not a problem though.', 'درست است. اما برای یک گربه معمولاً مشکلی نیست.'),
((SELECT id FROM lessons WHERE day = 102), 10, 'sent', NULL, 'Gut. Dürfte ich den Vertrag noch einen Tag mitnehmen und in Ruhe prüfen?', 'Good. Might I take the contract for another day and check it calmly?', 'خوب. می‌توانم قرارداد را یک روز دیگر ببرم و با دقت بررسی کنم؟'),
((SELECT id FROM lessons WHERE day = 102), 11, 'received', 'Selbstverständlich. Es wäre mir sogar lieber, wenn Sie alles genau prüfen.', NULL, 'Of course. I would actually prefer it if you checked everything carefully.', 'البته. حتی ترجیح می‌دهم همه‌چیز را دقیق بررسی کنید.'),
((SELECT id FROM lessons WHERE day = 102), 12, 'sent', NULL, 'Eine letzte Frage: Wird die Wohnung renoviert übergeben?', 'One last question: is the flat handed over renovated?', 'یک سؤال آخر: خانه بازسازی‌شده تحویل داده می‌شود؟'),
((SELECT id FROM lessons WHERE day = 102), 13, 'received', 'Die Wände werden neu gestrichen, der Boden bleibt wie er ist.', NULL, 'The walls will be repainted, the floor stays as it is.', 'دیوارها دوباره رنگ می‌شوند، کف همان‌طور می‌ماند.'),
((SELECT id FROM lessons WHERE day = 102), 14, 'sent', NULL, 'Damit bin ich einverstanden. Ich melde mich morgen mit meiner Entscheidung.', 'I agree to that. I will get in touch tomorrow with my decision.', 'با این موافقم. فردا تصمیمم را اطلاع می‌دهم.');

-- ── Day 103: At the Bürgeramt ───────────────────────────────────────────────
INSERT INTO sentences (lesson_id, sentence_order, role, audio_text, target_text, translation, translation_fa) VALUES
((SELECT id FROM lessons WHERE day = 103), 1, 'received', 'Guten Tag. Sie haben einen Termin zur Anmeldung, ist das richtig?', NULL, 'Good afternoon. You have an appointment for registration, is that right?', 'روز بخیر. برای ثبت نشانی وقت دارید، درست است؟'),
((SELECT id FROM lessons WHERE day = 103), 2, 'sent', NULL, 'Ja, um halb elf. Ich möchte meinen neuen Wohnsitz anmelden.', 'Yes, at half past ten. I would like to register my new address.', 'بله، ساعت ده و نیم. می‌خواهم نشانی جدیدم را ثبت کنم.'),
((SELECT id FROM lessons WHERE day = 103), 3, 'received', 'Dann brauche ich Ihren Ausweis und die Wohnungsgeberbestätigung.', NULL, 'Then I need your ID and the confirmation from your landlord.', 'پس شناسنامه و تأییدیهٔ مالک را لازم دارم.'),
((SELECT id FROM lessons WHERE day = 103), 4, 'sent', NULL, 'Hier bitte. Können Sie mir sagen, ob ich noch etwas anderes brauche?', 'Here you are. Can you tell me whether I need anything else?', 'بفرمایید. می‌توانید بگویید چیز دیگری هم لازم دارم؟'),
((SELECT id FROM lessons WHERE day = 103), 5, 'received', 'Nein, das genügt. Wissen Sie schon, seit wann Sie dort wohnen?', NULL, 'No, that is enough. Do you already know since when you have lived there?', 'نه، همین کافی است. می‌دانید از چه تاریخی آنجا زندگی می‌کنید؟'),
((SELECT id FROM lessons WHERE day = 103), 6, 'sent', NULL, 'Seit dem ersten März. Ich hoffe, ich habe die Frist nicht überschritten.', 'Since the first of March. I hope I have not missed the deadline.', 'از اول مارس. امیدوارم مهلت را از دست نداده باشم.'),
((SELECT id FROM lessons WHERE day = 103), 7, 'received', 'Die Anmeldung muss innerhalb von zwei Wochen erfolgen. Das passt gerade noch.', NULL, 'Registration has to take place within two weeks. That just about fits.', 'ثبت باید ظرف دو هفته انجام شود. همین‌طور به موقع است.'),
((SELECT id FROM lessons WHERE day = 103), 8, 'sent', NULL, 'Zum Glück. Wird meine Steuer-Identifikationsnummer automatisch zugeschickt?', 'Luckily. Will my tax identification number be sent automatically?', 'خوشبختانه. شمارهٔ شناسایی مالیاتی‌ام خودکار فرستاده می‌شود؟'),
((SELECT id FROM lessons WHERE day = 103), 9, 'received', 'Ja, per Post innerhalb von zwei bis drei Wochen. Die brauchen Sie für Ihren Arbeitgeber.', NULL, 'Yes, by post within two to three weeks. You need it for your employer.', 'بله، پستی ظرف دو تا سه هفته. برای کارفرمایتان لازمش دارید.'),
((SELECT id FROM lessons WHERE day = 103), 10, 'sent', NULL, 'Und wo kann ich erfahren, wie es mit der Rundfunkgebühr weitergeht?', 'And where can I find out what happens with the broadcasting fee?', 'و کجا می‌توانم بفهمم با هزینهٔ رسانه چه می‌شود؟'),
((SELECT id FROM lessons WHERE day = 103), 11, 'received', 'Der Beitragsservice schreibt Sie an. Anmelden müssen Sie sich dort selbst.', NULL, 'The fee service will write to you. You have to register there yourself.', 'ادارهٔ حق اشتراک برایتان نامه می‌فرستد. ثبت‌نام را باید خودتان انجام دهید.'),
((SELECT id FROM lessons WHERE day = 103), 12, 'sent', NULL, 'Verstanden. Bekomme ich heute eine Bestätigung mit?', 'Understood. Do I get a confirmation to take with me today?', 'فهمیدم. امروز تأییدیه‌ای هم می‌گیرم؟'),
((SELECT id FROM lessons WHERE day = 103), 13, 'received', 'Ja, die Meldebescheinigung drucke ich Ihnen gleich aus.', NULL, 'Yes, I will print the registration certificate for you right away.', 'بله، گواهی ثبت را همین حالا برایتان چاپ می‌کنم.'),
((SELECT id FROM lessons WHERE day = 103), 14, 'sent', NULL, 'Herzlichen Dank. Sie haben mir sehr geholfen.', 'Many thanks. You have helped me a great deal.', 'خیلی ممنون. خیلی کمکم کردید.');

-- ── Day 104: Opening a Bank Account ─────────────────────────────────────────
INSERT INTO sentences (lesson_id, sentence_order, role, audio_text, target_text, translation, translation_fa) VALUES
((SELECT id FROM lessons WHERE day = 104), 1, 'received', 'Willkommen. Was kann ich für Sie tun?', NULL, 'Welcome. What can I do for you?', 'خوش آمدید. چه کاری می‌توانم برایتان بکنم؟'),
((SELECT id FROM lessons WHERE day = 104), 2, 'sent', NULL, 'Ich möchte ein Girokonto eröffnen, mit dem ich auch mein Gehalt empfangen kann.', 'I would like to open a current account with which I can also receive my salary.', 'می‌خواهم حساب جاری باز کنم که حقوقم را هم با آن دریافت کنم.'),
((SELECT id FROM lessons WHERE day = 104), 3, 'received', 'Gern. Haben Sie einen Nachweis über Ihr Einkommen dabei?', NULL, 'Gladly. Do you have proof of your income with you?', 'با کمال میل. مدرک درآمدتان همراهتان است؟'),
((SELECT id FROM lessons WHERE day = 104), 4, 'sent', NULL, 'Ja, hier ist mein Arbeitsvertrag, den ich letzte Woche unterschrieben habe.', 'Yes, here is my employment contract, which I signed last week.', 'بله، این قرارداد کاری‌ام است که هفتهٔ پیش امضا کردم.'),
((SELECT id FROM lessons WHERE day = 104), 5, 'received', 'Perfekt. Möchten Sie ein Konto, für das monatliche Gebühren anfallen, oder ein kostenloses?', NULL, 'Perfect. Would you like an account for which monthly fees apply, or a free one?', 'عالی. حسابی می‌خواهید که کارمزد ماهانه دارد یا حساب رایگان؟'),
((SELECT id FROM lessons WHERE day = 104), 6, 'sent', NULL, 'Was ist denn der Unterschied? Ich hätte gern das günstigere Modell.', 'What is the difference then? I would prefer the cheaper option.', 'تفاوتشان چیست؟ گزینهٔ ارزان‌تر را ترجیح می‌دهم.'),
((SELECT id FROM lessons WHERE day = 104), 7, 'received', 'Beim kostenlosen Konto zahlen Sie nichts, solange monatlich Geld eingeht.', NULL, 'With the free account you pay nothing, as long as money comes in monthly.', 'در حساب رایگان چیزی پرداخت نمی‌کنید، تا وقتی ماهانه پولی واریز شود.'),
((SELECT id FROM lessons WHERE day = 104), 8, 'sent', NULL, 'Dann nehme ich das. Wie lange dauert es, bis ich die Karte bekomme?', 'Then I will take that one. How long does it take until I get the card?', 'پس همان را می‌گیرم. چقدر طول می‌کشد تا کارت را بگیرم؟'),
((SELECT id FROM lessons WHERE day = 104), 9, 'received', 'Die Karte und die PIN kommen getrennt, in etwa einer Woche.', NULL, 'The card and the PIN come separately, in about a week.', 'کارت و رمز جدا می‌آیند، حدود یک هفته.'),
((SELECT id FROM lessons WHERE day = 104), 10, 'sent', NULL, 'Kann ich das Konto schon vorher online nutzen, um eine Überweisung zu machen?', 'Can I use the account online before that, in order to make a transfer?', 'می‌توانم پیش از آن حساب را آنلاین استفاده کنم تا انتقالی انجام دهم؟'),
((SELECT id FROM lessons WHERE day = 104), 11, 'received', 'Sobald Sie die Zugangsdaten haben, ja. Die schicken wir Ihnen morgen per Post.', NULL, 'As soon as you have the login details, yes. We will send those tomorrow by post.', 'به محض اینکه اطلاعات ورود را داشته باشید، بله. فردا پستی می‌فرستیم.'),
((SELECT id FROM lessons WHERE day = 104), 12, 'sent', NULL, 'Gibt es eine Gebühr, wenn ich Geld ins Ausland überweise?', 'Is there a fee if I transfer money abroad?', 'اگر پول به خارج بفرستم کارمزد دارد؟'),
((SELECT id FROM lessons WHERE day = 104), 13, 'received', 'Innerhalb Europas nicht. Für andere Länder berechnen wir eine Pauschale.', NULL, 'Not within Europe. For other countries we charge a flat rate.', 'داخل اروپا نه. برای کشورهای دیگر مبلغ ثابتی می‌گیریم.'),
((SELECT id FROM lessons WHERE day = 104), 14, 'sent', NULL, 'Alles klar. Dann würde ich das Konto jetzt gern eröffnen.', 'All clear. Then I would like to open the account now.', 'خیلی خوب. پس حالا دوست دارم حساب را باز کنم.');

-- ── Day 105: A Problem With the Neighbour ───────────────────────────────────
INSERT INTO sentences (lesson_id, sentence_order, role, audio_text, target_text, translation, translation_fa) VALUES
((SELECT id FROM lessons WHERE day = 105), 1, 'sent', NULL, 'Entschuldigen Sie die Störung. Hätten Sie kurz Zeit für mich?', 'Sorry to disturb you. Would you have a moment for me?', 'ببخشید مزاحم شدم. کمی وقت دارید؟'),
((SELECT id FROM lessons WHERE day = 105), 2, 'received', 'Klar, kommen Sie rein. Ist etwas passiert?', NULL, 'Sure, come in. Has something happened?', 'حتماً، بفرمایید تو. اتفاقی افتاده؟'),
((SELECT id FROM lessons WHERE day = 105), 3, 'sent', NULL, 'Es geht um die Musik am Abend. Ich wollte das nicht gleich beim Vermieter melden.', 'It is about the music in the evening. I did not want to report it to the landlord straight away.', 'دربارهٔ موسیقی شب‌هاست. نخواستم فوراً به مالک بگویم.'),
((SELECT id FROM lessons WHERE day = 105), 4, 'received', 'Oh. Ist es wirklich so laut? Das war mir gar nicht bewusst.', NULL, 'Oh. Is it really that loud? I was not aware of that at all.', 'اوه. واقعاً این‌قدر بلند است؟ اصلاً متوجه نبودم.'),
((SELECT id FROM lessons WHERE day = 105), 5, 'sent', NULL, 'Nach zehn Uhr hört man es deutlich, obwohl die Wände eigentlich dick sind.', 'After ten o''clock you can hear it clearly, although the walls are actually thick.', 'بعد از ساعت ده واضح شنیده می‌شود، هرچند دیوارها در واقع ضخیم‌اند.'),
((SELECT id FROM lessons WHERE day = 105), 6, 'received', 'Das tut mir leid. Ich arbeite abends und vergesse dann die Zeit.', NULL, 'I am sorry about that. I work in the evenings and then lose track of time.', 'متأسفم. شب‌ها کار می‌کنم و زمان از دستم در می‌رود.'),
((SELECT id FROM lessons WHERE day = 105), 7, 'sent', NULL, 'Das verstehe ich gut. Könnten Sie nach zweiundzwanzig Uhr vielleicht Kopfhörer benutzen?', 'I understand that well. Could you perhaps use headphones after ten p.m.?', 'کاملاً درک می‌کنم. می‌شود بعد از ساعت ده از هدفون استفاده کنید؟'),
((SELECT id FROM lessons WHERE day = 105), 8, 'received', 'Das wäre kein Problem. Ich hätte selbst darauf kommen sollen.', NULL, 'That would be no problem. I should have thought of that myself.', 'مشکلی نیست. خودم باید به فکرش می‌افتادم.'),
((SELECT id FROM lessons WHERE day = 105), 9, 'sent', NULL, 'Danke, das ist sehr entgegenkommend von Ihnen.', 'Thank you, that is very accommodating of you.', 'ممنون، خیلی همراهی می‌کنید.'),
((SELECT id FROM lessons WHERE day = 105), 10, 'received', 'Sagen Sie mir bitte Bescheid, falls es trotzdem noch stört.', NULL, 'Please let me know if it still disturbs you anyway.', 'لطفاً خبرم کنید اگر باز هم مزاحم بود.'),
((SELECT id FROM lessons WHERE day = 105), 11, 'sent', NULL, 'Mache ich. Und wenn ich zu laut bin, sagen Sie es mir bitte auch.', 'I will. And if I am too loud, please tell me too.', 'حتماً. و اگر من هم بلند بودم، لطفاً بگویید.'),
((SELECT id FROM lessons WHERE day = 105), 12, 'received', 'Abgemacht. Es ist schön, dass wir direkt miteinander reden.', NULL, 'Agreed. It is nice that we talk to each other directly.', 'قبول. خوب است که مستقیم با هم حرف می‌زنیم.'),
((SELECT id FROM lessons WHERE day = 105), 13, 'sent', NULL, 'Finde ich auch. Sonst hätte das leicht zu Streit führen können.', 'I think so too. Otherwise that could easily have led to an argument.', 'من هم همین‌طور. وگرنه راحت می‌توانست به دعوا بکشد.'),
((SELECT id FROM lessons WHERE day = 105), 14, 'received', 'Genau. Schönen Abend noch, und bis bald.', NULL, 'Exactly. Have a nice evening, and see you soon.', 'دقیقاً. شب خوبی داشته باشید، به‌زودی می‌بینمتان.');

INSERT INTO lessons (day, title, title_fa, "group", sort_order, grammar_focus, grammar_focus_fa, difficulty) VALUES
(106, 'Day 106: Explaining Your Medical History', 'روز ۱۰۶: شرح سابقهٔ پزشکی', 'advanced', 106, 'seit + Dativ for duration; subordinate clauses of time; body vocabulary', 'seit + دادی برای مدت؛ جملات زمان؛ واژگان بدن', 'B1+'),
(107, 'Day 107: Talking About the News', 'روز ۱۰۷: صحبت دربارهٔ اخبار', 'advanced', 107, 'Indirect speech (soll, angeblich); expressing doubt; opinion frames', 'نقل قول غیرمستقیم (soll, angeblich)؛ بیان تردید؛ ساختار نظر دادن', 'B1+'),
(108, 'Day 108: Making a Formal Complaint', 'روز ۱۰۸: شکایت رسمی', 'advanced', 108, 'Passiv in complaints; darauf bestehen; escalating politely', 'مجهول در شکایت؛ darauf bestehen؛ تشدید محترمانه', 'B1+'),
(109, 'Day 109: Negotiating Your Salary', 'روز ۱۰۹: مذاکره بر سر حقوق', 'advanced', 109, 'Konjunktiv II throughout; nicht nur … sondern auch; hedging', 'التزامی دوم در سراسر؛ nicht nur … sondern auch؛ محافظه‌کاری در بیان', 'B1+'),
(110, 'Day 110: Clearing Up a Misunderstanding', 'روز ۱۱۰: رفع سوءتفاهم', 'advanced', 110, 'Plusquamperfekt; hätte … sollen; taking responsibility', 'گذشتهٔ بعید؛ hätte … sollen؛ پذیرفتن مسئولیت', 'B1+');

-- ── Day 106: Explaining Your Medical History ────────────────────────────────
INSERT INTO sentences (lesson_id, sentence_order, role, audio_text, target_text, translation, translation_fa) VALUES
((SELECT id FROM lessons WHERE day = 106), 1, 'received', 'Guten Tag. Was führt Sie heute zu mir?', NULL, 'Good afternoon. What brings you to me today?', 'روز بخیر. امروز چه چیزی شما را نزد من آورده؟'),
((SELECT id FROM lessons WHERE day = 106), 2, 'sent', NULL, 'Ich habe seit etwa drei Wochen Schmerzen im unteren Rücken.', 'I have had pain in my lower back for about three weeks.', 'حدود سه هفته است که در قسمت پایین کمرم درد دارم.'),
((SELECT id FROM lessons WHERE day = 106), 3, 'received', 'Sind die Schmerzen dauerhaft, oder treten sie nur bei Bewegung auf?', NULL, 'Is the pain constant, or does it only occur when you move?', 'درد دائمی است یا فقط هنگام حرکت پیش می‌آید؟'),
((SELECT id FROM lessons WHERE day = 106), 4, 'sent', NULL, 'Vor allem morgens, wenn ich aufstehe. Tagsüber wird es meistens besser.', 'Mainly in the mornings when I get up. During the day it usually gets better.', 'بیشتر صبح‌ها وقتی بلند می‌شوم. در طول روز معمولاً بهتر می‌شود.'),
((SELECT id FROM lessons WHERE day = 106), 5, 'received', 'Hatten Sie schon einmal ähnliche Beschwerden?', NULL, 'Have you had similar complaints before?', 'قبلاً هم چنین مشکلی داشته‌اید؟'),
((SELECT id FROM lessons WHERE day = 106), 6, 'sent', NULL, 'Vor zwei Jahren, nachdem ich beim Umzug schwer gehoben hatte.', 'Two years ago, after I had lifted something heavy during a move.', 'دو سال پیش، بعد از اینکه موقع اسباب‌کشی چیز سنگینی بلند کرده بودم.'),
((SELECT id FROM lessons WHERE day = 106), 7, 'received', 'Nehmen Sie regelmäßig Medikamente ein?', NULL, 'Do you take any medication regularly?', 'دارویی به‌طور منظم مصرف می‌کنید؟'),
((SELECT id FROM lessons WHERE day = 106), 8, 'sent', NULL, 'Nur ein Schmerzmittel, wenn es sehr weh tut. Sonst nichts.', 'Only a painkiller when it hurts a lot. Nothing else.', 'فقط مسکن وقتی خیلی درد دارد. غیر از آن هیچ.'),
((SELECT id FROM lessons WHERE day = 106), 9, 'received', 'Gibt es in Ihrer Familie Erkrankungen des Rückens oder der Gelenke?', NULL, 'Are there any back or joint conditions in your family?', 'در خانواده‌تان بیماری کمر یا مفاصل هست؟'),
((SELECT id FROM lessons WHERE day = 106), 10, 'sent', NULL, 'Meine Mutter hat Arthrose, aber erst seit sie über sechzig ist.', 'My mother has arthritis, but only since she turned sixty.', 'مادرم آرتروز دارد، اما فقط از وقتی بالای شصت سالش شده.'),
((SELECT id FROM lessons WHERE day = 106), 11, 'received', 'Ich taste jetzt kurz ab. Sagen Sie mir, wenn es unangenehm wird.', NULL, 'I will examine you briefly now. Tell me if it becomes uncomfortable.', 'حالا کمی معاینه می‌کنم. اگر ناراحت شد بگویید.'),
((SELECT id FROM lessons WHERE day = 106), 12, 'sent', NULL, 'Da, genau an dieser Stelle, ist es am schlimmsten.', 'There, exactly at that spot, it is worst.', 'همان‌جا، دقیقاً همین نقطه، بدترین است.'),
((SELECT id FROM lessons WHERE day = 106), 13, 'received', 'Das deutet auf eine Verspannung hin. Ich verschreibe Ihnen Physiotherapie.', NULL, 'That points to muscle tension. I will prescribe you physiotherapy.', 'نشان‌دهندهٔ گرفتگی عضله است. فیزیوتراپی برایتان می‌نویسم.'),
((SELECT id FROM lessons WHERE day = 106), 14, 'sent', NULL, 'Und falls es nicht besser wird, soll ich dann wiederkommen?', 'And if it does not get better, should I come back then?', 'و اگر بهتر نشد، باید دوباره بیایم؟'),
((SELECT id FROM lessons WHERE day = 106), 15, 'received', 'Ja, unbedingt. Dann machen wir eine genauere Untersuchung.', NULL, 'Yes, definitely. Then we will do a more detailed examination.', 'بله، حتماً. آن وقت معاینهٔ دقیق‌تری می‌کنیم.');

-- ── Day 107: Talking About the News ─────────────────────────────────────────
INSERT INTO sentences (lesson_id, sentence_order, role, audio_text, target_text, translation, translation_fa) VALUES
((SELECT id FROM lessons WHERE day = 107), 1, 'received', 'Hast du gehört, dass die Bahn wieder streiken soll?', NULL, 'Have you heard that the railway is supposedly going to strike again?', 'شنیدی که قرار است راه‌آهن دوباره اعتصاب کند؟'),
((SELECT id FROM lessons WHERE day = 107), 2, 'sent', NULL, 'Ja, es stand heute Morgen in den Nachrichten. Angeblich ab Montag.', 'Yes, it was in the news this morning. Supposedly from Monday.', 'بله، امروز صبح در اخبار بود. ظاهراً از دوشنبه.'),
((SELECT id FROM lessons WHERE day = 107), 3, 'received', 'Das ist schon der dritte Streik in diesem Jahr, oder?', NULL, 'That is already the third strike this year, isn''t it?', 'این سومین اعتصاب امسال است، نه؟'),
((SELECT id FROM lessons WHERE day = 107), 4, 'sent', NULL, 'Ich glaube sogar der vierte. Ehrlich gesagt kann ich beide Seiten verstehen.', 'I think it is even the fourth. Honestly, I can understand both sides.', 'فکر کنم حتی چهارمین. راستش هر دو طرف را درک می‌کنم.'),
((SELECT id FROM lessons WHERE day = 107), 5, 'received', 'Wirklich? Mich nervt es einfach nur. Ich komme dann nicht zur Arbeit.', NULL, 'Really? It just annoys me. I cannot get to work then.', 'واقعاً؟ من فقط کلافه می‌شوم. آن وقت به سر کار نمی‌رسم.'),
((SELECT id FROM lessons WHERE day = 107), 6, 'sent', NULL, 'Das stimmt schon. Andererseits verdienen die Angestellten seit Jahren zu wenig.', 'That is true. On the other hand the employees have been underpaid for years.', 'درست است. از طرف دیگر کارکنان سال‌هاست کم می‌گیرند.'),
((SELECT id FROM lessons WHERE day = 107), 7, 'received', 'Da hast du nicht ganz unrecht. Aber muss man deswegen das ganze Land lahmlegen?', NULL, 'You are not entirely wrong there. But does the whole country have to be paralysed for it?', 'کاملاً بی‌راه نمی‌گویی. اما آیا باید کل کشور را فلج کرد؟'),
((SELECT id FROM lessons WHERE day = 107), 8, 'sent', NULL, 'Sonst wird nicht verhandelt. Das ist leider die einzige Sprache, die verstanden wird.', 'Otherwise there is no negotiation. Sadly that is the only language that gets understood.', 'وگرنه مذاکره‌ای نمی‌شود. متأسفانه تنها زبانی است که فهمیده می‌شود.'),
((SELECT id FROM lessons WHERE day = 107), 9, 'received', 'Vielleicht. Liest du eigentlich noch Zeitung, oder alles online?', NULL, 'Maybe. Do you actually still read a newspaper, or everything online?', 'شاید. اصلاً هنوز روزنامه می‌خوانی یا همه‌چیز آنلاین؟'),
((SELECT id FROM lessons WHERE day = 107), 10, 'sent', NULL, 'Meistens online, aber am Wochenende kaufe ich mir gern eine gedruckte Zeitung.', 'Mostly online, but at the weekend I like to buy a printed newspaper.', 'بیشتر آنلاین، اما آخر هفته دوست دارم روزنامهٔ چاپی بخرم.'),
((SELECT id FROM lessons WHERE day = 107), 11, 'received', 'Das verstehe ich. Online liest man nur noch Überschriften.', NULL, 'I understand that. Online you only read headlines any more.', 'درکش می‌کنم. آنلاین فقط تیترها را می‌خوانی.'),
((SELECT id FROM lessons WHERE day = 107), 12, 'sent', NULL, 'Genau. Und man weiß oft nicht, ob eine Quelle überhaupt zuverlässig ist.', 'Exactly. And you often do not know whether a source is reliable at all.', 'دقیقاً. و اغلب نمی‌دانی منبع اصلاً معتبر است یا نه.'),
((SELECT id FROM lessons WHERE day = 107), 13, 'received', 'Deshalb schaue ich immer, wer den Artikel geschrieben hat.', NULL, 'That is why I always check who wrote the article.', 'برای همین همیشه نگاه می‌کنم چه کسی مقاله را نوشته.'),
((SELECT id FROM lessons WHERE day = 107), 14, 'sent', NULL, 'Kluge Angewohnheit. Ich sollte das auch öfter machen.', 'Wise habit. I should do that more often too.', 'عادت هوشمندانه‌ای است. من هم باید بیشتر این کار را بکنم.');

-- ── Day 108: Making a Formal Complaint ──────────────────────────────────────
INSERT INTO sentences (lesson_id, sentence_order, role, audio_text, target_text, translation, translation_fa) VALUES
((SELECT id FROM lessons WHERE day = 108), 1, 'sent', NULL, 'Guten Tag. Ich möchte mich über eine Lieferung beschweren.', 'Good afternoon. I would like to complain about a delivery.', 'روز بخیر. می‌خواهم دربارهٔ یک ارسال شکایت کنم.'),
((SELECT id FROM lessons WHERE day = 108), 2, 'received', 'Das tut mir leid. Können Sie mir die Bestellnummer nennen?', NULL, 'I am sorry about that. Can you give me the order number?', 'متأسفم. می‌توانید شمارهٔ سفارش را بگویید؟'),
((SELECT id FROM lessons WHERE day = 108), 3, 'sent', NULL, 'Ja, sie lautet vier-sieben-zwei-neun. Das Gerät wurde beschädigt geliefert.', 'Yes, it is four-seven-two-nine. The device was delivered damaged.', 'بله، چهار-هفت-دو-نه است. دستگاه آسیب‌دیده تحویل داده شد.'),
((SELECT id FROM lessons WHERE day = 108), 4, 'received', 'Ich sehe die Bestellung. Wurde der Schaden beim Empfang dokumentiert?', NULL, 'I can see the order. Was the damage documented on receipt?', 'سفارش را می‌بینم. آسیب هنگام تحویل ثبت شد؟'),
((SELECT id FROM lessons WHERE day = 108), 5, 'sent', NULL, 'Ja, ich habe Fotos gemacht und sie noch am selben Tag geschickt.', 'Yes, I took photos and sent them the same day.', 'بله، عکس گرفتم و همان روز فرستادم.'),
((SELECT id FROM lessons WHERE day = 108), 6, 'received', 'Die kann ich hier leider nicht finden. An welche Adresse wurden sie geschickt?', NULL, 'Unfortunately I cannot find them here. Which address were they sent to?', 'متأسفانه اینجا پیدایشان نمی‌کنم. به کدام نشانی فرستاده شدند؟'),
((SELECT id FROM lessons WHERE day = 108), 7, 'sent', NULL, 'An die Adresse im Bestätigungsmail. Ich kann sie Ihnen gern noch einmal senden.', 'To the address in the confirmation email. I am happy to send them again.', 'به نشانی داخل ایمیل تأیید. با کمال میل دوباره می‌فرستم.'),
((SELECT id FROM lessons WHERE day = 108), 8, 'received', 'Das wäre hilfreich. Möchten Sie einen Ersatz oder die Rückerstattung?', NULL, 'That would be helpful. Would you like a replacement or a refund?', 'کمک‌کننده است. جایگزین می‌خواهید یا بازپرداخت؟'),
((SELECT id FROM lessons WHERE day = 108), 9, 'sent', NULL, 'Ich bestehe auf einer vollständigen Rückerstattung, da ich das Gerät dringend gebraucht hätte.', 'I insist on a full refund, since I would have needed the device urgently.', 'بر بازپرداخت کامل اصرار دارم، چون فوری به دستگاه نیاز داشتم.'),
((SELECT id FROM lessons WHERE day = 108), 10, 'received', 'Das kann ich nachvollziehen. Die Bearbeitung dauert etwa zehn Werktage.', NULL, 'I can understand that. Processing takes about ten working days.', 'درک می‌کنم. رسیدگی حدود ده روز کاری طول می‌کشد.'),
((SELECT id FROM lessons WHERE day = 108), 11, 'sent', NULL, 'Zehn Tage finde ich zu lang. Ginge das nicht schneller?', 'I find ten days too long. Could that not be done faster?', 'ده روز به نظرم زیاد است. سریع‌تر نمی‌شود؟'),
((SELECT id FROM lessons WHERE day = 108), 12, 'received', 'Ich markiere den Fall als dringend. Dann sind es meistens fünf Tage.', NULL, 'I will mark the case as urgent. Then it is usually five days.', 'پرونده را فوری علامت می‌زنم. آن‌وقت معمولاً پنج روز است.'),
((SELECT id FROM lessons WHERE day = 108), 13, 'sent', NULL, 'Danke. Bekomme ich das bitte schriftlich bestätigt?', 'Thank you. Could I please have that confirmed in writing?', 'ممنون. می‌شود این را کتبی تأیید کنید؟'),
((SELECT id FROM lessons WHERE day = 108), 14, 'received', 'Selbstverständlich. Die Bestätigung geht in den nächsten Minuten per Mail raus.', NULL, 'Of course. The confirmation will go out by email in the next few minutes.', 'البته. تأییدیه ظرف چند دقیقهٔ آینده ایمیل می‌شود.');

-- ── Day 109: Negotiating Your Salary ────────────────────────────────────────
INSERT INTO sentences (lesson_id, sentence_order, role, audio_text, target_text, translation, translation_fa) VALUES
((SELECT id FROM lessons WHERE day = 109), 1, 'received', 'Sie wollten über Ihr Gehalt sprechen. Ich höre Ihnen zu.', NULL, 'You wanted to talk about your salary. I am listening.', 'می‌خواستید دربارهٔ حقوقتان صحبت کنید. گوش می‌دهم.'),
((SELECT id FROM lessons WHERE day = 109), 2, 'sent', NULL, 'Danke. Ich arbeite jetzt zwei Jahre hier und habe deutlich mehr Verantwortung übernommen.', 'Thank you. I have worked here two years now and taken on considerably more responsibility.', 'ممنون. حالا دو سال است اینجا کار می‌کنم و مسئولیت خیلی بیشتری گرفته‌ام.'),
((SELECT id FROM lessons WHERE day = 109), 3, 'received', 'Das sehe ich auch so. Woran denken Sie konkret?', NULL, 'I see it that way too. What do you have in mind specifically?', 'من هم همین‌طور می‌بینم. دقیقاً به چه فکر می‌کنید؟'),
((SELECT id FROM lessons WHERE day = 109), 4, 'sent', NULL, 'Ich hätte gern eine Anpassung auf das Niveau, das im Markt üblich ist.', 'I would like an adjustment to the level that is standard in the market.', 'دوست دارم به سطحی برسم که در بازار معمول است.'),
((SELECT id FROM lessons WHERE day = 109), 5, 'received', 'Haben Sie eine bestimmte Zahl im Kopf?', NULL, 'Do you have a particular figure in mind?', 'رقم مشخصی در ذهن دارید؟'),
((SELECT id FROM lessons WHERE day = 109), 6, 'sent', NULL, 'Ich würde acht Prozent für angemessen halten, gemessen an meinen Ergebnissen.', 'I would consider eight percent appropriate, measured against my results.', 'هشت درصد را با توجه به نتایجم مناسب می‌دانم.'),
((SELECT id FROM lessons WHERE day = 109), 7, 'received', 'Acht ist ambitioniert. Was genau meinen Sie mit Ergebnissen?', NULL, 'Eight is ambitious. What exactly do you mean by results?', 'هشت بلندپروازانه است. دقیقاً منظورتان از نتایج چیست؟'),
((SELECT id FROM lessons WHERE day = 109), 8, 'sent', NULL, 'Ich habe nicht nur zwei Projekte geleitet, sondern auch zwei neue Kollegen eingearbeitet.', 'I have not only led two projects but also trained two new colleagues.', 'نه‌تنها دو پروژه را رهبری کردم، بلکه دو همکار جدید را هم آموزش دادم.'),
((SELECT id FROM lessons WHERE day = 109), 9, 'received', 'Das ist mir bewusst. Fünf Prozent könnte ich sofort zusagen.', NULL, 'I am aware of that. Five percent I could agree to immediately.', 'می‌دانم. پنج درصد را می‌توانم فوراً قبول کنم.'),
((SELECT id FROM lessons WHERE day = 109), 10, 'sent', NULL, 'Wären sechs Prozent möglich, wenn wir in sechs Monaten noch einmal sprechen?', 'Would six percent be possible if we talk again in six months?', 'شش درصد ممکن است، اگر شش ماه دیگر دوباره صحبت کنیم؟'),
((SELECT id FROM lessons WHERE day = 109), 11, 'received', 'Das halte ich für fair. Sechs Prozent und ein Gespräch im Herbst.', NULL, 'I consider that fair. Six percent and a conversation in the autumn.', 'منصفانه می‌دانمش. شش درصد و یک گفت‌وگو در پاییز.'),
((SELECT id FROM lessons WHERE day = 109), 12, 'sent', NULL, 'Damit bin ich sehr zufrieden. Ab wann würde das gelten?', 'I am very happy with that. From when would it apply?', 'خیلی راضی‌ام. از کی اعمال می‌شود؟'),
((SELECT id FROM lessons WHERE day = 109), 13, 'received', 'Ab dem nächsten Monat. Den Nachtrag zum Vertrag bekommen Sie diese Woche.', NULL, 'From next month. You will get the contract amendment this week.', 'از ماه آینده. الحاقیهٔ قرارداد را همین هفته می‌گیرید.'),
((SELECT id FROM lessons WHERE day = 109), 14, 'sent', NULL, 'Vielen Dank, dass Sie sich die Zeit genommen haben.', 'Thank you very much for taking the time.', 'خیلی ممنون که وقت گذاشتید.');

-- ── Day 110: Clearing Up a Misunderstanding ─────────────────────────────────
INSERT INTO sentences (lesson_id, sentence_order, role, audio_text, target_text, translation, translation_fa) VALUES
((SELECT id FROM lessons WHERE day = 110), 1, 'received', 'Hast du kurz Zeit? Ich glaube, wir haben gestern aneinander vorbeigeredet.', NULL, 'Do you have a moment? I think we talked at cross purposes yesterday.', 'کمی وقت داری؟ فکر کنم دیروز حرف همدیگر را نفهمیدیم.'),
((SELECT id FROM lessons WHERE day = 110), 2, 'sent', NULL, 'Ja, das hatte ich auch das Gefühl. Was genau meinst du?', 'Yes, I had that feeling too. What exactly do you mean?', 'بله، من هم همین حس را داشتم. دقیقاً منظورت چیست؟'),
((SELECT id FROM lessons WHERE day = 110), 3, 'received', 'Ich dachte, du hättest den Bericht schon abgeschickt. Der Kunde hat nachgefragt.', NULL, 'I thought you had already sent the report. The client asked about it.', 'فکر کردم گزارش را فرستاده بودی. مشتری پرسیده بود.'),
((SELECT id FROM lessons WHERE day = 110), 4, 'sent', NULL, 'Oh nein. Ich hatte verstanden, dass du ihn vorher noch prüfen wolltest.', 'Oh no. I had understood that you wanted to check it first.', 'وای نه. من فهمیده بودم که می‌خواستی اول بررسی‌اش کنی.'),
((SELECT id FROM lessons WHERE day = 110), 5, 'received', 'Das war wohl mein Fehler. Ich hätte es deutlicher sagen sollen.', NULL, 'That was probably my mistake. I should have said it more clearly.', 'احتمالاً اشتباه من بود. باید واضح‌تر می‌گفتم.'),
((SELECT id FROM lessons WHERE day = 110), 6, 'sent', NULL, 'Und ich hätte nachfragen sollen, statt einfach zu warten.', 'And I should have asked, instead of simply waiting.', 'و من باید می‌پرسیدم، به‌جای اینکه فقط منتظر بمانم.'),
((SELECT id FROM lessons WHERE day = 110), 7, 'received', 'Dann sind wir beide schuld. Wichtiger ist, wie wir es jetzt lösen.', NULL, 'Then we are both at fault. What matters more is how we solve it now.', 'پس هر دو مقصریم. مهم‌تر این است که حالا چطور حلش کنیم.'),
((SELECT id FROM lessons WHERE day = 110), 8, 'sent', NULL, 'Ich kann den Bericht in einer Stunde fertig machen und direkt verschicken.', 'I can finish the report in an hour and send it directly.', 'می‌توانم گزارش را در یک ساعت تمام کنم و مستقیم بفرستم.'),
((SELECT id FROM lessons WHERE day = 110), 9, 'received', 'Perfekt. Ich schreibe dem Kunden inzwischen, dass es heute noch kommt.', NULL, 'Perfect. In the meantime I will write to the client that it is still coming today.', 'عالی. در این فاصله به مشتری می‌نویسم که امروز می‌رسد.'),
((SELECT id FROM lessons WHERE day = 110), 10, 'sent', NULL, 'Gute Idee. Sollen wir künftig kurz bestätigen, wer was übernimmt?', 'Good idea. Shall we briefly confirm in future who takes on what?', 'فکر خوبی است. از این به بعد کوتاه تأیید کنیم چه کسی چه کاری را برمی‌دارد؟'),
((SELECT id FROM lessons WHERE day = 110), 11, 'received', 'Unbedingt. Eine kurze Nachricht hätte uns beiden viel Ärger erspart.', NULL, 'Definitely. A short message would have saved us both a lot of trouble.', 'حتماً. یک پیام کوتاه هر دومان را از دردسر نجات می‌داد.'),
((SELECT id FROM lessons WHERE day = 110), 12, 'sent', NULL, 'Genau. Danke, dass du es direkt angesprochen hast.', 'Exactly. Thank you for bringing it up directly.', 'دقیقاً. ممنون که مستقیم مطرحش کردی.'),
((SELECT id FROM lessons WHERE day = 110), 13, 'received', 'Immer gern. Mir ist es lieber, wir klären so etwas sofort.', NULL, 'Any time. I prefer it when we clear something like this up immediately.', 'همیشه. ترجیح می‌دهم چنین چیزی را فوری روشن کنیم.'),
((SELECT id FROM lessons WHERE day = 110), 14, 'sent', NULL, 'Mir auch. Ich melde mich, sobald der Bericht raus ist.', 'Me too. I will let you know as soon as the report has gone out.', 'من هم. به محض اینکه گزارش رفت خبرت می‌کنم.');

INSERT INTO lessons (day, title, title_fa, "group", sort_order, grammar_focus, grammar_focus_fa, difficulty) VALUES
(111, 'Day 111: Discussing a Film', 'روز ۱۱۱: گفت‌وگو دربارهٔ یک فیلم', 'advanced', 111, 'Relative clauses; expressing nuanced opinion; es geht um', 'جملهٔ موصولی؛ بیان نظر ظریف؛ es geht um', 'B1+'),
(112, 'Day 112: Childhood Memories', 'روز ۱۱۲: خاطرات کودکی', 'advanced', 112, 'Präteritum in narrative; als vs wenn; damals', 'گذشتهٔ ساده در روایت؛ als در برابر wenn؛ damals', 'B1+'),
(113, 'Day 113: Insurance and Paperwork', 'روز ۱۱۳: بیمه و کاغذبازی', 'advanced', 113, 'Genitiv; conditional with sollte; formal written register', 'اضافه؛ شرط با sollte؛ لحن رسمی نوشتاری', 'B1+'),
(114, 'Day 114: Giving Feedback to a Colleague', 'روز ۱۱۴: بازخورد دادن به همکار', 'advanced', 114, 'Diplomatic softeners; mir ist aufgefallen; suggesting rather than telling', 'نرم‌کننده‌های دیپلماتیک؛ mir ist aufgefallen؛ پیشنهاد به‌جای دستور', 'B1+'),
(115, 'Day 115: Climate and Everyday Choices', 'روز ۱۱۵: اقلیم و انتخاب‌های روزمره', 'advanced', 115, 'Argumentation: einerseits/andererseits; je … desto; concessive trotzdem', 'استدلال: از سویی/از سوی دیگر؛ je … desto؛ trotzdem', 'B1+');

-- ── Day 111: Discussing a Film ──────────────────────────────────────────────
INSERT INTO sentences (lesson_id, sentence_order, role, audio_text, target_text, translation, translation_fa) VALUES
((SELECT id FROM lessons WHERE day = 111), 1, 'received', 'Und, wie hat dir der Film gefallen, den wir gestern gesehen haben?', NULL, 'So, how did you like the film that we watched yesterday?', 'خب، فیلمی که دیروز دیدیم چطور بود؟'),
((SELECT id FROM lessons WHERE day = 111), 2, 'sent', NULL, 'Besser als erwartet, ehrlich gesagt. Die erste Stunde fand ich allerdings zäh.', 'Better than expected, honestly. I did find the first hour slow though.', 'راستش بهتر از انتظارم بود. هرچند ساعت اول را کند دیدم.'),
((SELECT id FROM lessons WHERE day = 111), 3, 'received', 'Das ging mir genauso. Worum ging es deiner Meinung nach eigentlich?', NULL, 'I felt the same. What was it actually about, in your opinion?', 'من هم همین‌طور. به نظرت اصلاً موضوعش چه بود؟'),
((SELECT id FROM lessons WHERE day = 111), 4, 'sent', NULL, 'Für mich ging es weniger um die Politik als um die Familie, die daran zerbricht.', 'For me it was less about the politics than about the family that falls apart because of it.', 'برای من کمتر دربارهٔ سیاست بود و بیشتر دربارهٔ خانواده‌ای که از هم می‌پاشد.'),
((SELECT id FROM lessons WHERE day = 111), 5, 'received', 'Interessant. Ich hatte den Eindruck, die Regisseurin wollte vor allem provozieren.', NULL, 'Interesting. I had the impression the director mainly wanted to provoke.', 'جالب است. حس کردم کارگردان بیشتر می‌خواست تحریک کند.'),
((SELECT id FROM lessons WHERE day = 111), 6, 'sent', NULL, 'Möglich. Aber die Szene, in der die Tochter schweigt, war für mich das Stärkste.', 'Possibly. But the scene in which the daughter stays silent was the strongest part for me.', 'شاید. اما صحنه‌ای که دختر سکوت می‌کند برایم قوی‌ترین بود.'),
((SELECT id FROM lessons WHERE day = 111), 7, 'received', 'Da hast du recht. Ohne ein einziges Wort hat man alles verstanden.', NULL, 'You are right there. Without a single word you understood everything.', 'درست می‌گویی. بدون یک کلمه همه‌چیز را فهمیدی.'),
((SELECT id FROM lessons WHERE day = 111), 8, 'sent', NULL, 'Genau das meine ich. Solche Momente bleiben länger hängen als lange Dialoge.', 'That is exactly what I mean. Such moments stay with you longer than long dialogues.', 'دقیقاً همین را می‌گویم. چنین لحظه‌هایی بیشتر از گفت‌وگوهای طولانی می‌مانند.'),
((SELECT id FROM lessons WHERE day = 111), 9, 'received', 'Würdest du den Film weiterempfehlen?', NULL, 'Would you recommend the film?', 'فیلم را توصیه می‌کنی؟'),
((SELECT id FROM lessons WHERE day = 111), 10, 'sent', NULL, 'Schon, aber nicht jedem. Man braucht Geduld und sollte nicht müde sein.', 'Yes, but not to everyone. You need patience and should not be tired.', 'بله، اما نه به هرکسی. صبر می‌خواهد و نباید خسته باشی.'),
((SELECT id FROM lessons WHERE day = 111), 11, 'received', 'Das ist eine faire Einschätzung. Kennst du andere Filme von ihr?', NULL, 'That is a fair assessment. Do you know other films by her?', 'ارزیابی منصفانه‌ای است. فیلم‌های دیگرش را می‌شناسی؟'),
((SELECT id FROM lessons WHERE day = 111), 12, 'sent', NULL, 'Nur einen, der vor ein paar Jahren im Kino lief. Der war ähnlich ruhig.', 'Only one, which was in cinemas a few years ago. That one was similarly quiet.', 'فقط یکی که چند سال پیش روی پرده بود. آن هم به همان آرامی بود.'),
((SELECT id FROM lessons WHERE day = 111), 13, 'received', 'Dann schauen wir den beim nächsten Mal.', NULL, 'Then we will watch that one next time.', 'پس دفعهٔ بعد آن را می‌بینیم.'),
((SELECT id FROM lessons WHERE day = 111), 14, 'sent', NULL, 'Einverstanden, aber diesmal nicht so spät am Abend.', 'Agreed, but this time not so late in the evening.', 'قبول، اما این بار نه این‌قدر دیروقت.');

-- ── Day 112: Childhood Memories ─────────────────────────────────────────────
INSERT INTO sentences (lesson_id, sentence_order, role, audio_text, target_text, translation, translation_fa) VALUES
((SELECT id FROM lessons WHERE day = 112), 1, 'received', 'Wo bist du eigentlich aufgewachsen?', NULL, 'Where did you actually grow up?', 'راستی کجا بزرگ شدی؟'),
((SELECT id FROM lessons WHERE day = 112), 2, 'sent', NULL, 'In einer kleinen Stadt im Norden. Damals kannte dort noch jeder jeden.', 'In a small town in the north. Back then everyone still knew everyone there.', 'در شهر کوچکی در شمال. آن موقع همه همدیگر را می‌شناختند.'),
((SELECT id FROM lessons WHERE day = 112), 3, 'received', 'Das klingt schön. Was hast du als Kind am liebsten gemacht?', NULL, 'That sounds nice. What did you most like doing as a child?', 'قشنگ به نظر می‌رسد. بچه که بودی بیشتر از همه چه کار دوست داشتی؟'),
((SELECT id FROM lessons WHERE day = 112), 4, 'sent', NULL, 'Im Sommer waren wir jeden Tag am Fluss. Wir kamen erst zurück, wenn es dunkel wurde.', 'In summer we were at the river every day. We only came back when it got dark.', 'تابستان‌ها هر روز کنار رودخانه بودیم. فقط وقتی هوا تاریک می‌شد برمی‌گشتیم.'),
((SELECT id FROM lessons WHERE day = 112), 5, 'received', 'Und als du in die Schule kamst, hat sich das geändert?', NULL, 'And when you started school, did that change?', 'و وقتی به مدرسه رفتی، این عوض شد؟'),
((SELECT id FROM lessons WHERE day = 112), 6, 'sent', NULL, 'Erst später. Als ich zwölf war, zogen wir in eine größere Stadt.', 'Only later. When I was twelve, we moved to a bigger city.', 'بعدتر. وقتی دوازده ساله بودم، به شهر بزرگ‌تری نقل مکان کردیم.'),
((SELECT id FROM lessons WHERE day = 112), 7, 'received', 'War das schwierig für dich?', NULL, 'Was that difficult for you?', 'برایت سخت بود؟'),
((SELECT id FROM lessons WHERE day = 112), 8, 'sent', NULL, 'Am Anfang schon. Ich vermisste meine Freunde und fand die Stadt viel zu laut.', 'At first, yes. I missed my friends and found the city far too loud.', 'اولش بله. دلم برای دوستانم تنگ می‌شد و شهر را خیلی شلوغ می‌دیدم.'),
((SELECT id FROM lessons WHERE day = 112), 9, 'received', 'Und heute? Würdest du wieder aufs Land ziehen?', NULL, 'And today? Would you move to the countryside again?', 'و حالا؟ دوباره به روستا می‌رفتی؟'),
((SELECT id FROM lessons WHERE day = 112), 10, 'sent', NULL, 'Vielleicht später. Im Moment brauche ich die Möglichkeiten, die eine Stadt bietet.', 'Maybe later. At the moment I need the opportunities a city offers.', 'شاید بعدها. الان به فرصت‌هایی که شهر می‌دهد نیاز دارم.'),
((SELECT id FROM lessons WHERE day = 112), 11, 'received', 'Das verstehe ich. Erinnerst du dich noch an deine erste Lehrerin?', NULL, 'I understand that. Do you still remember your first teacher?', 'درک می‌کنم. هنوز اولین معلمت را به یاد داری؟'),
((SELECT id FROM lessons WHERE day = 112), 12, 'sent', NULL, 'Sehr gut sogar. Sie war streng, aber sie hat an mich geglaubt.', 'Very well, in fact. She was strict, but she believed in me.', 'حتی خیلی خوب. سخت‌گیر بود، اما به من باور داشت.'),
((SELECT id FROM lessons WHERE day = 112), 13, 'received', 'Solche Menschen vergisst man nie.', NULL, 'You never forget people like that.', 'چنین آدم‌هایی را هرگز فراموش نمی‌کنی.'),
((SELECT id FROM lessons WHERE day = 112), 14, 'sent', NULL, 'Nein. Ohne sie hätte ich wahrscheinlich nie studiert.', 'No. Without her I probably would never have studied.', 'نه. بدون او احتمالاً هرگز دانشگاه نمی‌رفتم.');

-- ── Day 113: Insurance and Paperwork ────────────────────────────────────────
INSERT INTO sentences (lesson_id, sentence_order, role, audio_text, target_text, translation, translation_fa) VALUES
((SELECT id FROM lessons WHERE day = 113), 1, 'sent', NULL, 'Guten Tag, ich habe eine Frage zum Umfang meiner Versicherung.', 'Good afternoon, I have a question about the scope of my insurance.', 'روز بخیر، دربارهٔ دامنهٔ بیمه‌ام سؤالی دارم.'),
((SELECT id FROM lessons WHERE day = 113), 2, 'received', 'Gern. Um welche Versicherung handelt es sich?', NULL, 'Gladly. Which insurance is it about?', 'بفرمایید. کدام بیمه است؟'),
((SELECT id FROM lessons WHERE day = 113), 3, 'sent', NULL, 'Um die Haftpflichtversicherung. Ich habe versehentlich das Fahrrad eines Nachbarn beschädigt.', 'The liability insurance. I accidentally damaged a neighbour''s bicycle.', 'بیمهٔ مسئولیت. ناخواسته دوچرخهٔ یکی از همسایه‌ها را خراب کردم.'),
((SELECT id FROM lessons WHERE day = 113), 4, 'received', 'Das ist in der Regel abgedeckt. Wurde der Schaden bereits geschätzt?', NULL, 'That is generally covered. Has the damage already been estimated?', 'معمولاً پوشش دارد. خسارت برآورد شده؟'),
((SELECT id FROM lessons WHERE day = 113), 5, 'sent', NULL, 'Noch nicht. Sollte ich zuerst einen Kostenvoranschlag einholen?', 'Not yet. Should I first obtain a cost estimate?', 'هنوز نه. اول باید برآورد هزینه بگیرم؟'),
((SELECT id FROM lessons WHERE day = 113), 6, 'received', 'Ja, das erleichtert die Bearbeitung des Antrags erheblich.', NULL, 'Yes, that makes processing the claim considerably easier.', 'بله، رسیدگی به درخواست را خیلی آسان‌تر می‌کند.'),
((SELECT id FROM lessons WHERE day = 113), 7, 'sent', NULL, 'Gibt es eine Frist, innerhalb derer ich den Schaden melden muss?', 'Is there a deadline within which I have to report the damage?', 'مهلتی هست که باید در آن خسارت را گزارش کنم؟'),
((SELECT id FROM lessons WHERE day = 113), 8, 'received', 'Eine Woche nach Kenntnis des Schadens. Sie sind also noch im Rahmen.', NULL, 'One week after becoming aware of the damage. So you are still within it.', 'یک هفته پس از اطلاع از خسارت. پس هنوز در مهلت هستید.'),
((SELECT id FROM lessons WHERE day = 113), 9, 'sent', NULL, 'Beruhigend. Muss ich eine Selbstbeteiligung zahlen?', 'Reassuring. Do I have to pay an excess?', 'خیال‌آسوده‌کننده است. باید سهم خودم را بپردازم؟'),
((SELECT id FROM lessons WHERE day = 113), 10, 'received', 'In Ihrem Tarif beträgt die Selbstbeteiligung einhundertfünfzig Euro.', NULL, 'In your plan the excess is one hundred and fifty euros.', 'در طرح شما سهم شخصی صد و پنجاه یورو است.'),
((SELECT id FROM lessons WHERE day = 113), 11, 'sent', NULL, 'Verstanden. Sollte der Schaden geringer sein, lohnt sich die Meldung also nicht.', 'Understood. So if the damage is smaller, reporting it is not worth it.', 'فهمیدم. پس اگر خسارت کمتر باشد، گزارش دادن نمی‌ارزد.'),
((SELECT id FROM lessons WHERE day = 113), 12, 'received', 'Genau. Rechnen Sie erst, und melden Sie dann.', NULL, 'Exactly. Do the sums first, and report afterwards.', 'دقیقاً. اول حساب کنید، بعد گزارش دهید.'),
((SELECT id FROM lessons WHERE day = 113), 13, 'sent', NULL, 'Das mache ich. Kann ich den Antrag online einreichen?', 'I will do that. Can I submit the claim online?', 'همین کار را می‌کنم. می‌توانم درخواست را آنلاین بفرستم؟'),
((SELECT id FROM lessons WHERE day = 113), 14, 'received', 'Ja, über Ihr Kundenkonto. Dort laden Sie die Fotos und den Voranschlag hoch.', NULL, 'Yes, through your customer account. There you upload the photos and the estimate.', 'بله، از طریق حساب کاربری‌تان. آنجا عکس‌ها و برآورد را بارگذاری می‌کنید.');

-- ── Day 114: Giving Feedback to a Colleague ─────────────────────────────────
INSERT INTO sentences (lesson_id, sentence_order, role, audio_text, target_text, translation, translation_fa) VALUES
((SELECT id FROM lessons WHERE day = 114), 1, 'sent', NULL, 'Hast du fünf Minuten? Ich wollte kurz über die Präsentation sprechen.', 'Do you have five minutes? I wanted to talk briefly about the presentation.', 'پنج دقیقه وقت داری؟ می‌خواستم کوتاه دربارهٔ ارائه صحبت کنم.'),
((SELECT id FROM lessons WHERE day = 114), 2, 'received', 'Klar. War etwas nicht gut?', NULL, 'Sure. Was something not good?', 'حتماً. چیزی خوب نبود؟'),
((SELECT id FROM lessons WHERE day = 114), 3, 'sent', NULL, 'Im Gegenteil, der Inhalt war stark. Mir ist nur eine Kleinigkeit aufgefallen.', 'On the contrary, the content was strong. I just noticed one small thing.', 'برعکس، محتوا قوی بود. فقط یک نکتهٔ کوچک به چشمم آمد.'),
((SELECT id FROM lessons WHERE day = 114), 4, 'received', 'Sag ruhig. Ich höre lieber jetzt als nach dem Kundentermin.', NULL, 'Go ahead. I would rather hear it now than after the client meeting.', 'راحت بگو. ترجیح می‌دهم حالا بشنوم تا بعد از جلسهٔ مشتری.'),
((SELECT id FROM lessons WHERE day = 114), 5, 'sent', NULL, 'Die Folien waren sehr dicht. Vielleicht würde weniger Text stärker wirken.', 'The slides were very dense. Perhaps less text would come across as stronger.', 'اسلایدها خیلی پر بودند. شاید متن کمتر مؤثرتر باشد.'),
((SELECT id FROM lessons WHERE day = 114), 6, 'received', 'Das höre ich nicht zum ersten Mal. Ich habe Angst, etwas Wichtiges wegzulassen.', NULL, 'That is not the first time I have heard that. I am afraid of leaving out something important.', 'اولین بار نیست که این را می‌شنوم. می‌ترسم چیز مهمی را جا بیندازم.'),
((SELECT id FROM lessons WHERE day = 114), 7, 'sent', NULL, 'Das verstehe ich gut. Du könntest die Details in den Anhang nehmen.', 'I understand that well. You could move the details into the appendix.', 'کاملاً درک می‌کنم. می‌توانی جزئیات را به پیوست منتقل کنی.'),
((SELECT id FROM lessons WHERE day = 114), 8, 'received', 'Guter Vorschlag. Dann bleibt die Hauptfolie ruhig und ich habe trotzdem alles dabei.', NULL, 'Good suggestion. Then the main slide stays calm and I still have everything with me.', 'پیشنهاد خوبی است. آن‌وقت اسلاید اصلی آرام می‌ماند و همه‌چیز را هم دارم.'),
((SELECT id FROM lessons WHERE day = 114), 9, 'sent', NULL, 'Genau so hätte ich es gemacht. Ansonsten war der Aufbau wirklich klar.', 'That is exactly how I would have done it. Otherwise the structure was really clear.', 'دقیقاً همین‌طور انجامش می‌دادم. غیر از آن ساختار واقعاً روشن بود.'),
((SELECT id FROM lessons WHERE day = 114), 10, 'received', 'Danke, dass du es mir direkt sagst und nicht im Meeting.', NULL, 'Thank you for telling me directly and not in the meeting.', 'ممنون که مستقیم گفتی و نه در جلسه.'),
((SELECT id FROM lessons WHERE day = 114), 11, 'sent', NULL, 'So möchte ich es umgekehrt auch. Sag mir bitte, wenn dir etwas auffällt.', 'I would want the same in reverse. Please tell me if you notice anything.', 'برعکسش را هم همین‌طور می‌خواهم. اگر چیزی دیدی لطفاً بگو.'),
((SELECT id FROM lessons WHERE day = 114), 12, 'received', 'Mache ich. Schaust du dir die neue Version morgen noch einmal an?', NULL, 'I will. Will you look at the new version again tomorrow?', 'حتماً. فردا نسخهٔ جدید را دوباره نگاه می‌کنی؟'),
((SELECT id FROM lessons WHERE day = 114), 13, 'sent', NULL, 'Gern, schick sie mir einfach, sobald du fertig bist.', 'Happily, just send it to me as soon as you are done.', 'با کمال میل، هر وقت تمام شد برایم بفرست.'),
((SELECT id FROM lessons WHERE day = 114), 14, 'received', 'Perfekt. Bis morgen dann.', NULL, 'Perfect. See you tomorrow then.', 'عالی. پس تا فردا.');

-- ── Day 115: Climate and Everyday Choices ───────────────────────────────────
INSERT INTO sentences (lesson_id, sentence_order, role, audio_text, target_text, translation, translation_fa) VALUES
((SELECT id FROM lessons WHERE day = 115), 1, 'received', 'Fährst du eigentlich immer noch mit dem Auto zur Arbeit?', NULL, 'Do you actually still drive to work?', 'راستی هنوز با ماشین سر کار می‌روی؟'),
((SELECT id FROM lessons WHERE day = 115), 2, 'sent', NULL, 'Seltener als früher. Einerseits ist es bequem, andererseits stehe ich ständig im Stau.', 'Less often than before. On the one hand it is comfortable, on the other I am constantly stuck in traffic.', 'کمتر از قبل. از سویی راحت است، از سوی دیگر مدام در ترافیک می‌مانم.'),
((SELECT id FROM lessons WHERE day = 115), 3, 'received', 'Je mehr Leute umsteigen, desto besser wird der Verkehr für alle.', NULL, 'The more people switch, the better the traffic becomes for everyone.', 'هرچه بیشتر مردم عوض کنند، ترافیک برای همه بهتر می‌شود.'),
((SELECT id FROM lessons WHERE day = 115), 4, 'sent', NULL, 'Theoretisch ja. Aber bei uns fährt der Bus nur alle vierzig Minuten.', 'In theory yes. But where I live the bus only runs every forty minutes.', 'در تئوری بله. اما جای ما اتوبوس هر چهل دقیقه یک بار می‌آید.'),
((SELECT id FROM lessons WHERE day = 115), 5, 'received', 'Das ist natürlich ein Argument. Trotzdem finde ich, jeder kann etwas tun.', NULL, 'That is of course an argument. Nevertheless I think everyone can do something.', 'البته این هم دلیلی است. با این حال فکر می‌کنم هرکس می‌تواند کاری بکند.'),
((SELECT id FROM lessons WHERE day = 115), 6, 'sent', NULL, 'Da stimme ich zu. Ich habe angefangen, weniger Fleisch zu essen.', 'I agree with that. I have started eating less meat.', 'موافقم. شروع کرده‌ام کمتر گوشت بخورم.'),
((SELECT id FROM lessons WHERE day = 115), 7, 'received', 'Fällt dir das schwer?', NULL, 'Do you find that difficult?', 'برایت سخت است؟'),
((SELECT id FROM lessons WHERE day = 115), 8, 'sent', NULL, 'Weniger, als ich dachte. Man gewöhnt sich schneller daran, als man glaubt.', 'Less than I thought. You get used to it faster than you believe.', 'کمتر از آنچه فکر می‌کردم. زودتر از تصور آدم عادت می‌کنی.'),
((SELECT id FROM lessons WHERE day = 115), 9, 'received', 'Manche sagen, individuelle Entscheidungen ändern ohnehin nichts.', NULL, 'Some people say individual decisions change nothing anyway.', 'بعضی‌ها می‌گویند تصمیم‌های فردی به‌هرحال چیزی را عوض نمی‌کند.'),
((SELECT id FROM lessons WHERE day = 115), 10, 'sent', NULL, 'Das halte ich für eine bequeme Ausrede. Politik entsteht auch aus Gewohnheiten.', 'I consider that a convenient excuse. Politics also grows out of habits.', 'این را بهانه‌ای راحت می‌دانم. سیاست هم از عادت‌ها شکل می‌گیرد.'),
((SELECT id FROM lessons WHERE day = 115), 11, 'received', 'Interessanter Gedanke. So hatte ich das noch nicht gesehen.', NULL, 'Interesting thought. I had not seen it that way before.', 'فکر جالبی است. این‌طور ندیده بودمش.'),
((SELECT id FROM lessons WHERE day = 115), 12, 'sent', NULL, 'Natürlich braucht es beides: bessere Gesetze und andere Gewohnheiten.', 'Of course you need both: better laws and different habits.', 'البته هر دو لازم است: قوانین بهتر و عادت‌های متفاوت.'),
((SELECT id FROM lessons WHERE day = 115), 13, 'received', 'Damit kann ich leben. Sollen wir nächste Woche mal zusammen mit dem Rad fahren?', NULL, 'I can live with that. Shall we cycle together next week?', 'با این کنار می‌آیم. هفتهٔ آینده با هم دوچرخه برویم؟'),
((SELECT id FROM lessons WHERE day = 115), 14, 'sent', NULL, 'Sehr gern, wenn es nicht regnet. Sonst nehme ich doch wieder den Bus.', 'Very gladly, if it does not rain. Otherwise I will take the bus after all.', 'با کمال میل، اگر باران نبارد. وگرنه باز هم اتوبوس می‌گیرم.');


INSERT INTO lessons (day, title, title_fa, "group", sort_order, grammar_focus, grammar_focus_fa, difficulty) VALUES
(116, 'Day 116: Explaining a Decision You Regret', 'روز ۱۱۶: توضیح تصمیمی که پشیمانی', 'advanced', 116, 'Konjunktiv II Vergangenheit (hätte gemacht); regret and hindsight', 'التزامی دوم گذشته (hätte gemacht)؛ پشیمانی و نگاه به گذشته', 'B1+'),
(117, 'Day 117: A Difficult Phone Call', 'روز ۱۱۷: یک تماس تلفنی دشوار', 'advanced', 117, 'Telephone register; asking for repetition; spelling aloud', 'لحن تلفنی؛ درخواست تکرار؛ هجی کردن', 'B1+'),
(118, 'Day 118: Describing How Something Works', 'روز ۱۱۸: توضیح طرز کار یک چیز', 'advanced', 118, 'Passiv in process description; zuerst/anschließend/schließlich', 'مجهول در شرح فرآیند؛ اول/سپس/در نهایت', 'B1+'),
(119, 'Day 119: Disagreeing Without Offending', 'روز ۱۱۹: مخالفت بدون رنجاندن', 'advanced', 119, 'Concessive clauses; das mag sein, aber; holding a position politely', 'جملات امتیازی؛ das mag sein, aber؛ حفظ موضع با ادب', 'B1+'),
(120, 'Day 120: The Last Lesson', 'روز ۱۲۰: آخرین درس', 'advanced', 120, 'Review of the whole path; werden future; reflective Konjunktiv II', 'مرور کل مسیر؛ آیندهٔ werden؛ التزامی دوم بازتابی', 'B1+');

-- ── Day 116: Explaining a Decision You Regret ───────────────────────────────
INSERT INTO sentences (lesson_id, sentence_order, role, audio_text, target_text, translation, translation_fa) VALUES
((SELECT id FROM lessons WHERE day = 116), 1, 'received', 'Du wirkst nachdenklich. Ist alles in Ordnung?', NULL, 'You seem thoughtful. Is everything all right?', 'متفکر به نظر می‌رسی. همه‌چیز خوب است؟'),
((SELECT id FROM lessons WHERE day = 116), 2, 'sent', NULL, 'Ich denke über das Jobangebot nach, das ich letztes Jahr abgelehnt habe.', 'I am thinking about the job offer that I turned down last year.', 'دارم به پیشنهاد کاری فکر می‌کنم که پارسال رد کردم.'),
((SELECT id FROM lessons WHERE day = 116), 3, 'received', 'Bereust du die Entscheidung?', NULL, 'Do you regret the decision?', 'از آن تصمیم پشیمانی؟'),
((SELECT id FROM lessons WHERE day = 116), 4, 'sent', NULL, 'Manchmal. Ich hätte zumindest mit meiner Familie darüber sprechen sollen.', 'Sometimes. I should at least have talked to my family about it.', 'گاهی. دست‌کم باید با خانواده‌ام دربارهٔ آن حرف می‌زدم.'),
((SELECT id FROM lessons WHERE day = 116), 5, 'received', 'Warum hast du das nicht getan?', NULL, 'Why did you not do that?', 'چرا این کار را نکردی؟'),
((SELECT id FROM lessons WHERE day = 116), 6, 'sent', NULL, 'Ich hatte Angst, dass sie mich überreden würden, und wollte allein entscheiden.', 'I was afraid they would persuade me, and I wanted to decide alone.', 'می‌ترسیدم راضی‌ام کنند و می‌خواستم خودم تصمیم بگیرم.'),
((SELECT id FROM lessons WHERE day = 116), 7, 'received', 'Das kann ich nachvollziehen. Wärst du denn glücklicher geworden?', NULL, 'I can understand that. Would you have become happier then?', 'درک می‌کنم. آن‌وقت خوشحال‌تر می‌شدی؟'),
((SELECT id FROM lessons WHERE day = 116), 8, 'sent', NULL, 'Wer weiß. Vielleicht hätte ich dieselben Probleme in einer anderen Stadt gehabt.', 'Who knows. Perhaps I would have had the same problems in another city.', 'کسی چه می‌داند. شاید همان مشکلات را در شهری دیگر داشتم.'),
((SELECT id FROM lessons WHERE day = 116), 9, 'received', 'Genau das denke ich auch. Man vergleicht die Wirklichkeit immer mit einer Fantasie.', NULL, 'That is exactly what I think too. You always compare reality with a fantasy.', 'دقیقاً من هم همین را فکر می‌کنم. آدم همیشه واقعیت را با خیال مقایسه می‌کند.'),
((SELECT id FROM lessons WHERE day = 116), 10, 'sent', NULL, 'Stimmt. Und im Nachhinein sieht jede Alternative besser aus.', 'True. And in hindsight every alternative looks better.', 'درست است. و در نگاه به گذشته هر گزینهٔ دیگری بهتر به نظر می‌رسد.'),
((SELECT id FROM lessons WHERE day = 116), 11, 'received', 'Was würdest du beim nächsten Mal anders machen?', NULL, 'What would you do differently next time?', 'دفعهٔ بعد چه کاری را متفاوت انجام می‌دادی؟'),
((SELECT id FROM lessons WHERE day = 116), 12, 'sent', NULL, 'Ich würde mir mehr Zeit nehmen und offener über meine Zweifel sprechen.', 'I would take more time and speak more openly about my doubts.', 'وقت بیشتری می‌گذاشتم و آشکارتر از تردیدهایم می‌گفتم.'),
((SELECT id FROM lessons WHERE day = 116), 13, 'received', 'Dann war die Entscheidung vielleicht falsch, aber du hast etwas daraus gelernt.', NULL, 'Then the decision was perhaps wrong, but you learned something from it.', 'پس شاید تصمیم اشتباه بود، اما چیزی از آن یاد گرفتی.'),
((SELECT id FROM lessons WHERE day = 116), 14, 'sent', NULL, 'So sehe ich es inzwischen auch. Danke, dass du zugehört hast.', 'That is how I see it now too. Thank you for listening.', 'حالا من هم همین‌طور می‌بینمش. ممنون که گوش دادی.');

-- ── Day 117: A Difficult Phone Call ─────────────────────────────────────────
INSERT INTO sentences (lesson_id, sentence_order, role, audio_text, target_text, translation, translation_fa) VALUES
((SELECT id FROM lessons WHERE day = 117), 1, 'received', 'Müller, guten Tag. Was kann ich für Sie tun?', NULL, 'Müller speaking, good afternoon. What can I do for you?', 'مولر هستم، روز بخیر. چه کاری می‌توانم برایتان بکنم؟'),
((SELECT id FROM lessons WHERE day = 117), 2, 'sent', NULL, 'Guten Tag. Es geht um meinen Antrag, der seit sechs Wochen bearbeitet wird.', 'Good afternoon. It is about my application, which has been in processing for six weeks.', 'روز بخیر. دربارهٔ درخواستم است که شش هفته در حال بررسی است.'),
((SELECT id FROM lessons WHERE day = 117), 3, 'received', 'Könnten Sie mir Ihr Aktenzeichen nennen?', NULL, 'Could you give me your reference number?', 'می‌توانید شمارهٔ پرونده‌تان را بگویید؟'),
((SELECT id FROM lessons WHERE day = 117), 4, 'sent', NULL, 'Entschuldigung, könnten Sie das bitte wiederholen? Die Verbindung ist schlecht.', 'Sorry, could you repeat that please? The connection is bad.', 'ببخشید، می‌شود دوباره بگویید؟ ارتباط بد است.'),
((SELECT id FROM lessons WHERE day = 117), 5, 'received', 'Natürlich. Ich brauche Ihr Aktenzeichen, die Nummer auf dem Schreiben.', NULL, 'Of course. I need your reference number, the number on the letter.', 'البته. شمارهٔ پرونده‌تان را لازم دارم، همان شماره روی نامه.'),
((SELECT id FROM lessons WHERE day = 117), 6, 'sent', NULL, 'Ah, verstanden. Sie lautet B wie Berta, drei, sieben, neun.', 'Ah, understood. It is B as in Berta, three, seven, nine.', 'آها، فهمیدم. B مثل برتا، سه، هفت، نه.'),
((SELECT id FROM lessons WHERE day = 117), 7, 'received', 'Danke. Einen Moment bitte, ich sehe im System nach.', NULL, 'Thank you. One moment please, I will check in the system.', 'ممنون. یک لحظه لطفاً، در سامانه نگاه می‌کنم.'),
((SELECT id FROM lessons WHERE day = 117), 8, 'sent', NULL, 'Kein Problem, ich warte.', 'No problem, I will wait.', 'مشکلی نیست، منتظر می‌مانم.'),
((SELECT id FROM lessons WHERE day = 117), 9, 'received', 'Ihr Antrag liegt bei der Prüfstelle. Es fehlt noch eine Unterschrift.', NULL, 'Your application is with the review office. One signature is still missing.', 'درخواستتان نزد بخش بررسی است. هنوز یک امضا کم دارد.'),
((SELECT id FROM lessons WHERE day = 117), 10, 'sent', NULL, 'Das höre ich zum ersten Mal. Mir wurde gesagt, alles sei vollständig.', 'That is the first I have heard of it. I was told everything was complete.', 'اولین بار است می‌شنوم. به من گفته بودند همه‌چیز کامل است.'),
((SELECT id FROM lessons WHERE day = 117), 11, 'received', 'Das tut mir leid. Ich schicke Ihnen das Formular heute noch per Mail.', NULL, 'I am sorry about that. I will send you the form by email today.', 'متأسفم. فرم را همین امروز ایمیل می‌کنم.'),
((SELECT id FROM lessons WHERE day = 117), 12, 'sent', NULL, 'Danke. Und wie lange dauert es, nachdem ich es zurückgeschickt habe?', 'Thank you. And how long does it take after I have sent it back?', 'ممنون. و بعد از اینکه پسش فرستادم چقدر طول می‌کشد؟'),
((SELECT id FROM lessons WHERE day = 117), 13, 'received', 'Etwa zwei Wochen. Ich notiere, dass der Fall vorrangig behandelt wird.', NULL, 'About two weeks. I will note that the case is to be handled with priority.', 'حدود دو هفته. یادداشت می‌کنم که پرونده در اولویت رسیدگی باشد.'),
((SELECT id FROM lessons WHERE day = 117), 14, 'sent', NULL, 'Das weiß ich zu schätzen. Vielen Dank für Ihre Hilfe. Auf Wiederhören.', 'I appreciate that. Thank you very much for your help. Goodbye.', 'قدردانی می‌کنم. خیلی ممنون از کمکتان. خداحافظ.');

-- ── Day 118: Describing How Something Works ─────────────────────────────────
INSERT INTO sentences (lesson_id, sentence_order, role, audio_text, target_text, translation, translation_fa) VALUES
((SELECT id FROM lessons WHERE day = 118), 1, 'received', 'Kannst du mir erklären, wie das Pfandsystem hier funktioniert?', NULL, 'Can you explain to me how the deposit system works here?', 'می‌توانی توضیح دهی سیستم ودیعهٔ بطری اینجا چطور کار می‌کند؟'),
((SELECT id FROM lessons WHERE day = 118), 2, 'sent', NULL, 'Gern. Zuerst zahlst du beim Kauf einen Aufschlag auf die Flasche.', 'Gladly. First you pay a surcharge on the bottle when you buy it.', 'با کمال میل. اول موقع خرید مبلغی اضافه روی بطری می‌دهی.'),
((SELECT id FROM lessons WHERE day = 118), 3, 'received', 'Wie viel ist das ungefähr?', NULL, 'How much is that roughly?', 'تقریباً چقدر است؟'),
((SELECT id FROM lessons WHERE day = 118), 4, 'sent', NULL, 'Zwischen acht und fünfundzwanzig Cent, je nachdem, ob die Flasche wiederverwendet wird.', 'Between eight and twenty-five cents, depending on whether the bottle is reused.', 'بین هشت تا بیست‌وپنج سنت، بسته به اینکه بطری دوباره استفاده شود یا نه.'),
((SELECT id FROM lessons WHERE day = 118), 5, 'received', 'Und dann? Was mache ich mit den leeren Flaschen?', NULL, 'And then? What do I do with the empty bottles?', 'و بعد؟ با بطری‌های خالی چه کنم؟'),
((SELECT id FROM lessons WHERE day = 118), 6, 'sent', NULL, 'Anschließend bringst du sie zum Automaten, der meistens im Supermarkt steht.', 'Afterwards you take them to the machine, which is usually in the supermarket.', 'سپس آن‌ها را به دستگاهی می‌بری که معمولاً در سوپرمارکت است.'),
((SELECT id FROM lessons WHERE day = 118), 7, 'received', 'Muss die Flasche unbeschädigt sein?', NULL, 'Does the bottle have to be undamaged?', 'بطری باید سالم باشد؟'),
((SELECT id FROM lessons WHERE day = 118), 8, 'sent', NULL, 'Ja, sonst wird der Strichcode nicht erkannt und die Flasche wird abgelehnt.', 'Yes, otherwise the barcode is not recognised and the bottle is rejected.', 'بله، وگرنه بارکد خوانده نمی‌شود و بطری پس زده می‌شود.'),
((SELECT id FROM lessons WHERE day = 118), 9, 'received', 'Verstehe. Und wie bekomme ich mein Geld zurück?', NULL, 'I see. And how do I get my money back?', 'فهمیدم. و پولم را چطور پس می‌گیرم؟'),
((SELECT id FROM lessons WHERE day = 118), 10, 'sent', NULL, 'Schließlich druckt der Automat einen Bon, den du an der Kasse einlöst.', 'Finally the machine prints a receipt, which you redeem at the till.', 'در نهایت دستگاه رسیدی چاپ می‌کند که سر صندوق نقدش می‌کنی.'),
((SELECT id FROM lessons WHERE day = 118), 11, 'received', 'Kann ich den Bon auch für den Einkauf verwenden?', NULL, 'Can I also use the receipt for my shopping?', 'می‌توانم رسید را برای خرید هم استفاده کنم؟'),
((SELECT id FROM lessons WHERE day = 118), 12, 'sent', NULL, 'Genau, das machen die meisten. Der Betrag wird einfach abgezogen.', 'Exactly, that is what most people do. The amount is simply deducted.', 'دقیقاً، بیشتر مردم همین کار را می‌کنند. مبلغ کسر می‌شود.'),
((SELECT id FROM lessons WHERE day = 118), 13, 'received', 'Das ist eigentlich ein kluges System.', NULL, 'That is actually a clever system.', 'در واقع سیستم هوشمندانه‌ای است.'),
((SELECT id FROM lessons WHERE day = 118), 14, 'sent', NULL, 'Finde ich auch. Man wirft kaum noch eine Flasche einfach weg.', 'I think so too. Hardly anyone simply throws a bottle away any more.', 'من هم همین‌طور. تقریباً دیگر کسی بطری را دور نمی‌اندازد.');

-- ── Day 119: Disagreeing Without Offending ──────────────────────────────────
INSERT INTO sentences (lesson_id, sentence_order, role, audio_text, target_text, translation, translation_fa) VALUES
((SELECT id FROM lessons WHERE day = 119), 1, 'received', 'Ich finde, wir sollten das Projekt komplett neu aufsetzen.', NULL, 'I think we should set up the project completely anew.', 'به نظرم باید پروژه را کاملاً از نو بچینیم.'),
((SELECT id FROM lessons WHERE day = 119), 2, 'sent', NULL, 'Das mag sein, aber ich sehe darin auch ein erhebliches Risiko.', 'That may be so, but I also see a considerable risk in it.', 'شاید، اما در آن ریسک قابل توجهی هم می‌بینم.'),
((SELECT id FROM lessons WHERE day = 119), 3, 'received', 'Welches Risiko meinst du konkret?', NULL, 'Which risk do you mean specifically?', 'دقیقاً کدام ریسک را می‌گویی؟'),
((SELECT id FROM lessons WHERE day = 119), 4, 'sent', NULL, 'Wir würden drei Monate verlieren, obwohl der Kunde im Juni liefern will.', 'We would lose three months, although the client wants to deliver in June.', 'سه ماه از دست می‌دهیم، درحالی‌که مشتری می‌خواهد ژوئن تحویل شود.'),
((SELECT id FROM lessons WHERE day = 119), 5, 'received', 'Da ist etwas dran. Trotzdem halte ich die jetzige Struktur für zu instabil.', NULL, 'There is something in that. Nevertheless I consider the current structure too unstable.', 'حرفت بی‌راه نیست. با این حال ساختار فعلی را ناپایدار می‌دانم.'),
((SELECT id FROM lessons WHERE day = 119), 6, 'sent', NULL, 'Dem widerspreche ich nicht. Könnten wir nicht schrittweise umbauen?', 'I do not dispute that. Could we not rebuild it step by step?', 'مخالفتی ندارم. نمی‌شود مرحله‌به‌مرحله بازسازی کنیم؟'),
((SELECT id FROM lessons WHERE day = 119), 7, 'received', 'Wie stellst du dir das vor?', NULL, 'How do you imagine that?', 'چطور تصورش می‌کنی؟'),
((SELECT id FROM lessons WHERE day = 119), 8, 'sent', NULL, 'Wir ersetzen zuerst den kritischsten Teil und lassen den Rest vorerst laufen.', 'We first replace the most critical part and let the rest run for now.', 'اول بحرانی‌ترین بخش را عوض می‌کنیم و بقیه فعلاً کار کند.'),
((SELECT id FROM lessons WHERE day = 119), 9, 'received', 'Das klingt vernünftiger, als ich zugeben möchte.', NULL, 'That sounds more sensible than I would like to admit.', 'منطقی‌تر از آن است که بخواهم اعتراف کنم.'),
((SELECT id FROM lessons WHERE day = 119), 10, 'sent', NULL, 'Dein Punkt war ja berechtigt. Ich möchte nur den Termin nicht gefährden.', 'Your point was valid after all. I just do not want to jeopardise the deadline.', 'نکتهٔ تو درست بود. فقط نمی‌خواهم موعد به خطر بیفتد.'),
((SELECT id FROM lessons WHERE day = 119), 11, 'received', 'Einverstanden. Schreibst du den Vorschlag auf, damit wir ihn vorstellen können?', NULL, 'Agreed. Will you write the proposal up so that we can present it?', 'قبول. پیشنهاد را می‌نویسی تا ارائه‌اش کنیم؟'),
((SELECT id FROM lessons WHERE day = 119), 12, 'sent', NULL, 'Mache ich bis morgen. Schau bitte drüber, bevor ich ihn verschicke.', 'I will do it by tomorrow. Please look over it before I send it.', 'تا فردا انجام می‌دهم. لطفاً پیش از فرستادن نگاهش کن.'),
((SELECT id FROM lessons WHERE day = 119), 13, 'received', 'Gern. Schön, dass wir uns nicht gestritten, sondern geeinigt haben.', NULL, 'Gladly. Good that we did not argue but reached agreement.', 'با کمال میل. خوب شد که دعوا نکردیم و به توافق رسیدیم.'),
((SELECT id FROM lessons WHERE day = 119), 14, 'sent', NULL, 'Das war mir wichtig. Am Ende wollen wir beide dasselbe.', 'That mattered to me. In the end we both want the same thing.', 'برایم مهم بود. آخرش هر دو یک چیز می‌خواهیم.');

-- ── Day 120: The Last Lesson ────────────────────────────────────────────────
INSERT INTO sentences (lesson_id, sentence_order, role, audio_text, target_text, translation, translation_fa) VALUES
((SELECT id FROM lessons WHERE day = 120), 1, 'received', 'Das ist die letzte Lektion. Wie fühlst du dich?', NULL, 'This is the last lesson. How do you feel?', 'این آخرین درس است. چه حسی داری؟'),
((SELECT id FROM lessons WHERE day = 120), 2, 'sent', NULL, 'Ehrlich gesagt gemischt. Stolz, aber auch ein bisschen wehmütig.', 'Honestly, mixed. Proud, but also a little wistful.', 'راستش حس‌های مختلط. مغرور، اما کمی دلتنگ هم.'),
((SELECT id FROM lessons WHERE day = 120), 3, 'received', 'Das kann ich verstehen. Woran erinnerst du dich am liebsten?', NULL, 'I can understand that. What do you remember most fondly?', 'درک می‌کنم. از چه چیزی بیشتر خاطرهٔ خوب داری؟'),
((SELECT id FROM lessons WHERE day = 120), 4, 'sent', NULL, 'An den Tag, an dem ich zum ersten Mal einen ganzen Satz ohne Nachdenken gesagt habe.', 'The day I said a whole sentence for the first time without thinking.', 'روزی که برای اولین بار یک جملهٔ کامل را بدون فکر گفتم.'),
((SELECT id FROM lessons WHERE day = 120), 5, 'received', 'Das ist der Moment, auf den alles hinausläuft.', NULL, 'That is the moment everything is aiming at.', 'همان لحظه‌ای است که همه‌چیز به آن ختم می‌شود.'),
((SELECT id FROM lessons WHERE day = 120), 6, 'sent', NULL, 'Am Anfang hätte ich nicht geglaubt, dass ich so weit kommen würde.', 'At the beginning I would not have believed I would get this far.', 'اولش باور نمی‌کردم این‌قدر پیش بروم.'),
((SELECT id FROM lessons WHERE day = 120), 7, 'received', 'Was war für dich am schwierigsten?', NULL, 'What was hardest for you?', 'چه چیزی برایت سخت‌ترین بود؟'),
((SELECT id FROM lessons WHERE day = 120), 8, 'sent', NULL, 'Die Wortstellung. Dass das Verb ans Ende wandert, hat lange keinen Sinn ergeben.', 'The word order. That the verb wanders to the end made no sense for a long time.', 'ترتیب کلمات. اینکه فعل به آخر می‌رود مدت‌ها بی‌معنا بود.'),
((SELECT id FROM lessons WHERE day = 120), 9, 'received', 'Und jetzt machst du es, ohne darüber nachzudenken.', NULL, 'And now you do it without thinking about it.', 'و حالا بدون فکر کردن انجامش می‌دهی.'),
((SELECT id FROM lessons WHERE day = 120), 10, 'sent', NULL, 'Stimmt. Genau das ist wohl der Unterschied zwischen Lernen und Können.', 'True. That is probably exactly the difference between learning and being able.', 'درست است. احتمالاً همین تفاوت یاد گرفتن و توانستن است.'),
((SELECT id FROM lessons WHERE day = 120), 11, 'received', 'Wie wirst du weitermachen, jetzt wo der Kurs zu Ende ist?', NULL, 'How will you continue, now that the course is over?', 'حالا که دوره تمام شده چطور ادامه می‌دهی؟'),
((SELECT id FROM lessons WHERE day = 120), 12, 'sent', NULL, 'Ich werde die Wiederholungen weiter machen und mir echte Gespräche suchen.', 'I will keep doing the reviews and look for real conversations.', 'مرورها را ادامه می‌دهم و دنبال گفت‌وگوهای واقعی می‌گردم.'),
((SELECT id FROM lessons WHERE day = 120), 13, 'received', 'Das ist genau der richtige Weg. Eine Sprache endet nie bei einer letzten Lektion.', NULL, 'That is exactly the right way. A language never ends at a last lesson.', 'دقیقاً راه درست همین است. یک زبان هرگز با آخرین درس تمام نمی‌شود.'),
((SELECT id FROM lessons WHERE day = 120), 14, 'sent', NULL, 'Das weiß ich jetzt. Danke für hundertzwanzig Tage Geduld.', 'I know that now. Thank you for one hundred and twenty days of patience.', 'حالا می‌دانم. ممنون بابت صد و بیست روز صبوری.'),
((SELECT id FROM lessons WHERE day = 120), 15, 'received', 'Es war mir ein Vergnügen. Viel Erfolg auf Deutsch, und bis bald!', NULL, 'It was my pleasure. Good luck in German, and see you soon!', 'باعث خوشحالی‌ام بود. در آلمانی موفق باشی، به‌زودی می‌بینمت!');

COMMIT;
