<script lang="ts">
  import type { InsightsReport } from '$lib/analytics/report';
  import { SOURCES, SOURCE_LABELS } from '$lib/analytics/phase-three';
  let { report, inspect }: { report: InsightsReport['phaseThree']['acquisition']; inspect: (id: string) => void } = $props();
  let source = $state('friend'), copied = $state(false);
  const link = $derived(`https://www.mirifer.com/?utm_source=${source}`);
  const rate = (n: number, d: number) => d ? `${Math.round(100*n/d)}%` : 'Not available';
  async function copy() { try { await navigator.clipboard.writeText(link); copied = true; } catch { copied = false; } }
</script>
<div class="analysis-view"><span class="analysis-eyebrow">ACQUISITION SOURCES</span><h2>Find where engaged learners come from.</h2><p>Compare new accounts by their first captured entry category. This report begins at signup; it does not count anonymous visitors.</p>
  <div class="analysis-metrics"><article><span>New accounts</span><strong>{report.signups}</strong><small>Created in the selected period</small></article><article><span>Entry captured near signup</span><strong>{report.observed}</strong><small>First saved attribution; later visits do not overwrite it</small></article><article><span>Unknown source</span><strong>{report.unknown}</strong><small>Missing capture or unrecognised tag</small></article><article><span>Established-account entries</span><strong>{report.existingEntries}</strong><small>Recorded in the period; excluded from signup attribution</small></article></div>
  <div class="analysis-table"><table><caption class="sr-only">Engagement by signup source</caption><thead><tr><th>Source</th><th>Signups</th><th>Practised in 24h</th><th>Finished a lesson in 7d</th><th>Learning return in 7d</th><th>Technical obstacles in 7d</th></tr></thead><tbody>{#each report.groups as group}<tr><td><button onclick={() => inspect(group.userIds[0])}>{group.label}</button><small>Inspect an example learner</small>{#if group.untracked}<small>{group.untracked} accounts predate tracked coverage</small>{/if}</td><td>{group.signups}</td>{#each [group.activation,group.completion,group.return,group.obstacle] as metric}<td>{rate(metric.count,metric.eligible)}<small>{metric.count} / {metric.eligible} eligible · {metric.pending} pending</small></td>{/each}</tr>{:else}<tr><td colspan="6" class="analysis-empty">No new accounts in the selected period.</td></tr>{/each}</tbody></table></div>
  <p class="analysis-note">Rates use accounts created after versioned tracking began, with a full 24-hour or seven-day observation window. Return means learning in another visit at least 24 hours after the first learning activity, within seven days of signup. This signup-based denominator differs from Return Visits, which starts its clock at the first learning visit.</p>
  <section class="analysis-panel"><h3>Create a source link</h3><p>Use a tagged link when sharing the app so a private chat or email does not appear as direct traffic.</p><div class="analysis-controls"><label>Source<select bind:value={source} onchange={() => copied = false}>{#each SOURCES.filter(s => !['direct','unknown','other_referral'].includes(s)) as s}<option value={s}>{SOURCE_LABELS[s]}</option>{/each}</select></label><label>Link<input readonly value={link} aria-label="Source link" onclick={e => e.currentTarget.select()} /></label><button onclick={copy}>{copied ? 'Copied' : 'Copy link'}</button></div></section>
  <details class="analysis-rules"><summary>Attribution definitions and limits</summary><ul><li>An allowlisted utm_source tag takes precedence over a recognised external referrer. With neither, the category is direct / no referrer. Browsers and private messages can hide referrers, so direct does not prove someone typed the address.</li><li>The browser keeps its first observed category for up to 30 days. It is linked after sign-in and saved once per account. Signup attribution requires capture before or within five minutes of account creation and sign-in within seven days of creation. Later first observations are classified as established-account entries.</li><li>Storage clearing, switching devices during confirmation and blocked requests can lose attribution. Unknown is kept separate; it is not reassigned to direct. Full referrer URLs and arbitrary campaign strings are not saved.</li><li>These counts cannot calculate visitor-to-signup conversion or acquisition cost. Differences between sources are descriptive and may reflect different learners, not the quality of a channel.</li></ul></details>
</div>
