<script lang="ts">
  import type { InsightsReport } from '$lib/analytics/report';
  import { CHANGE_METRICS, type ProductChange } from '$lib/analytics/phase-three';
  import { enhance } from '$app/forms';
  let { changes, days, includeTests }: { changes: InsightsReport['phaseThree']['changes']; days: number; includeTests: boolean } = $props();
  let editing = $state(''), title = $state(''), hypothesis = $state(''), shipped = $state(new Date().toISOString().slice(0,16)), windowDays = $state(7), metric = $state<keyof typeof CHANGE_METRICS>('completion');
  let showArchived = $state(false);
  const visible = $derived(changes.filter(c => showArchived || !c.archived));
  const action = $derived(`?/saveChange&tab=changes&days=${days}${includeTests ? '&tests=1' : ''}`);
  const archiveAction = $derived(`?/archiveChange&tab=changes&days=${days}${includeTests ? '&tests=1' : ''}`);
  const date = (s: string) => new Date(s).toLocaleDateString('en-GB', { timeZone:'UTC' });
  const percent = (n: number, d: number) => d ? `${Math.round(100*n/d)}%` : 'Not available';
  function edit(c: ProductChange) { editing = c.id; title = c.title; hypothesis = c.hypothesis; shipped = new Date(c.shipped_at).toISOString().slice(0,16); windowDays = c.window_days; metric = c.metric; document.getElementById('change-editor')?.scrollIntoView({ behavior:'smooth' }); }
  function reset() { editing = ''; title = ''; hypothesis = ''; shipped = new Date().toISOString().slice(0,16); windowDays = 7; metric = 'completion'; }
</script>
<div class="analysis-view"><span class="analysis-eyebrow">CHANGES & RESULTS</span><h2>Keep a record of what you changed.</h2><p>Write down the expected effect, then compare signup groups with equal follow-up time.</p>
  <p class="analysis-notice">These are historical before-and-after comparisons, not randomised experiments. A difference does not establish cause. New traffic sources, seasonality and overlapping changes can also affect results.</p>
  <div class="analysis-controls"><label class="archive-toggle"><input type="checkbox" bind:checked={showArchived} /> Show archived entries</label></div>
  {#each visible as change}
    <article class="analysis-panel change-result"><div class="analysis-heading"><div><span class="analysis-eyebrow">{date(change.shipped_at)} · {change.archived ? 'ARCHIVED' : 'SHIPPED'}</span><h3>{change.title}</h3></div><button onclick={() => edit(change)}>Edit entry</button></div><p>{change.hypothesis}</p><p><b>{CHANGE_METRICS[change.metric]}</b></p>
      <div class="analysis-metrics three">{#each [{ label:'Before', value:change.before },{ label:'After', value:change.after }] as side}<article><span>{side.label}</span><strong>{side.value.covered ? percent(side.value.count,side.value.eligible) : 'Not available'}</strong><small>{side.value.covered ? `${side.value.count} / ${side.value.eligible} eligible · ${side.value.pending} pending` : 'Tracking did not cover the full signup window'}</small><small>Signups: {date(side.value.start)} to before {date(side.value.end)}<br />{side.value.signups} observed accounts</small></article>{/each}<article><span>Difference in percentage points</span><strong>{change.difference === null ? 'Not available' : `${change.difference > 0 ? '+' : ''}${change.difference.toFixed(1)} pp`}</strong><small>{change.ready ? 'Both groups fully observed; descriptive comparison' : !change.before.covered || !change.after.covered ? 'Full baseline and follow-up coverage required' : !change.after.mature ? `After group matures ${date(change.after.readyAt)}` : 'Both groups need eligible learners'}</small></article></div>
      <p class="analysis-note">Each signup group spans {change.window_days} days. The before group ends seven days before rollout so all of its follow-up happens before the change. After signup closes, allow seven more days before comparing. A lower obstacle rate is favourable; other metrics favour a higher rate.</p>
      <form method="POST" action={archiveAction}><input type="hidden" name="id" value={change.id} /><input type="hidden" name="archived" value={change.archived ? '0' : '1'} /><button>{change.archived ? 'Restore entry' : 'Archive entry'}</button></form>
    </article>
  {:else}<div class="analysis-panel"><h3>No change entries in this period.</h3><p>Record a real product change below. Use the date it went live; earlier comparisons will stay unavailable if tracking did not cover them.</p></div>{/each}
  <section class="analysis-panel" id="change-editor"><h3>{editing ? 'Edit product change' : 'Record a product change'}</h3><form method="POST" action={action} use:enhance={() => async ({ result, update }) => { await update({ reset: false }); if (result.type === 'success') reset(); }} class="change-form"><input type="hidden" name="id" value={editing} /><label>What changed?<input name="title" bind:value={title} required maxlength="120" placeholder="Example: shorter introduction before lesson one" /></label><label>What do you expect, and why?<textarea name="hypothesis" bind:value={hypothesis} required maxlength="600" rows="3" placeholder="Example: fewer setup screens should help more new learners finish their first lesson."></textarea></label><div class="analysis-controls"><label>Went live (UTC)<input type="datetime-local" name="shipped_at" bind:value={shipped} required /></label><label>Signup window per group<select name="window_days" bind:value={windowDays}><option value={7}>7 days</option><option value={14}>14 days</option><option value={30}>30 days</option></select></label><label>Main outcome<select name="metric" bind:value={metric}>{#each Object.entries(CHANGE_METRICS) as [value,label]}<option {value}>{label}</option>{/each}</select></label></div><p class="analysis-note">Record your hypothesis before reviewing results. Editing the date, window or metric recalculates the comparison. Saving here documents a change; it does not modify learner features.</p><button class="save-change">{editing ? 'Save entry' : 'Add change'}</button>{#if editing}<button type="button" onclick={reset}>Cancel editing</button>{/if}</form></section>
</div>
<style>
  .change-result { margin:22px 0; } #change-editor { margin-top:28px; scroll-margin-top:20px; } .change-form>label { display:flex; flex-direction:column; gap:8px; font-size:.85rem; color:#b9c7bd; margin:18px 0; } .change-form :is(input,textarea) { box-sizing:border-box; font:inherit; background:#1c2823; border:1px solid #45544e; color:#f0f3ed; border-radius:6px; padding:12px; width:100%; max-width:100%; } .change-form textarea:focus-visible { outline:2px solid #b6dd94; outline-offset:3px; } .change-form .save-change { background:#b6dd94; color:#18231f; padding:12px 20px; border-radius:7px; margin-inline-end:22px; } .analysis-controls .archive-toggle { flex-direction:row; align-items:center; } .archive-toggle input { width:18px; min-height:18px; accent-color:#b6dd94; }
</style>
