<script lang="ts">
  import type { InsightsReport } from '$lib/analytics/report';
  let { report, inspect }: { report: InsightsReport['phaseThree']['assessments']; inspect: (id: string) => void } = $props();
  let checkpoint = $state(14), page = $state(0);
  const summary = $derived(report.checkpoints.find(c => c.day === Number(checkpoint))!);
  const rows = $derived(report.rows.slice(page * 12, (page + 1) * 12));
  const number = (n: number | null) => n === null ? 'Not available' : n.toFixed(1);
  const delta = (n: number | null) => n === null ? 'Not available' : `${n > 0 ? '+' : ''}${n.toFixed(1)}`;
  const date = (s: string | null) => s ? new Date(s).toLocaleDateString('en-GB', { timeZone:'UTC' }) : 'Not completed';
  $effect(() => { report; page = 0; });
</script>
<div class="analysis-view">
  <span class="analysis-eyebrow">LEARNING CHECKS</span><h2>Measure change in understanding.</h2><p>Pair each learner’s baseline with later checks. Keep missing follow-ups visible beside the scores.</p>
  <div class="analysis-metrics"><article><span>Completed baselines</span><strong>{report.completed}</strong><small>Baseline completion falls in the selected period</small></article><article><span>Unfinished baselines</span><strong>{report.unfinished}</strong><small>Started in the period; no saved completion</small></article><article><span>Baseline listening</span><strong>{number(report.baselineListening)} <em>/ 6</em></strong><small>{report.completed} completed checks</small></article><article><span>Baseline reading</span><strong>{number(report.baselineReading)} <em>/ 6</em></strong><small>{report.completed} completed checks</small></article></div>
  <p class="analysis-notice">Pilot comprehension checks, protocol de-check-v1. Six listening and six reading questions; speaking and writing are not assessed. These scores are not a CEFR level, a percentage of German learned, or evidence that the app caused improvement.</p>
  <h3>Follow-up coverage and paired scores</h3><div class="analysis-table"><table><caption class="sr-only">Follow-up learning checks</caption><thead><tr><th>Checkpoint</th><th>Window opened</th><th>Paired results</th><th>Not due yet</th><th>Window closed, missing</th><th>Listening change / 6</th><th>Reading change / 6</th></tr></thead><tbody>{#each report.checkpoints as c}<tr><td><button onclick={() => checkpoint = c.day}>Day {c.day}</button><small>Days {c.day}–{c.through} after baseline</small></td><td>{c.eligible}</td><td>{c.paired} / {c.eligible}</td><td>{c.pending}</td><td>{c.overdue}</td><td>{delta(c.listeningChange)}</td><td>{delta(c.readingChange)}</td></tr>{/each}</tbody></table></div>
  <p class="analysis-note">Changes are mean differences in correct answers for the same learners, using only saved results inside each checkpoint window. A missing follow-up is not a zero score. Results can change while a window remains open.</p>
  <div class="analysis-controls"><label>Inspect checkpoint<select bind:value={checkpoint}>{#each report.checkpoints as c}<option value={c.day}>Day {c.day}</option>{/each}</select></label></div>
  <div class="analysis-metrics three"><article><span>Mean total change / 12</span><strong>{delta(summary.totalChange)}</strong><small>{summary.paired} matched learners</small></article><article><span>Median time between checks</span><strong>{number(summary.medianElapsedDays)} <em>days</em></strong><small>Observed pairs only</small></article><article><span>Question-set coverage</span><strong>{summary.formPairs.map(p => `${p.form.toUpperCase()}: ${p.count}`).join(' · ')}</strong><small>Pairs by baseline form; alternate sets are not calibrated to equal difficulty</small></article></div>
  <div class="analysis-table"><table><caption class="sr-only">Individual learning check results</caption><thead><tr><th>Learner</th><th>Baseline</th><th>Day {checkpoint}</th><th>Total change / 12</th></tr></thead><tbody>{#each rows as row}{@const point = row.checkpoints.find(c => c.day === Number(checkpoint))!}<tr><td><button onclick={() => inspect(row.id)}>{row.label}</button><small>{row.priorPractice ? 'Practice observed before baseline' : 'No earlier practice observed'}</small></td><td>{row.baseline.listening_correct}/6 listening · {row.baseline.reading_correct}/6 reading<small>{date(row.baseline.completed_at)} · Set {row.baseline.form.toUpperCase()}</small></td><td>{#if point.result}{point.result.listening_correct}/6 listening · {point.result.reading_correct}/6 reading<small>{date(point.result.completed_at)} · Set {point.result.form.toUpperCase()}</small>{:else}{point.closed ? 'Window closed · no result' : point.eligible ? 'Due · no result' : 'Not due yet'}{/if}</td><td>{delta(point.delta)}</td></tr>{:else}<tr><td class="analysis-empty" colspan="4">No completed baseline in this period. Learners can start an optional check from their home page.</td></tr>{/each}</tbody></table></div>
  <div class="analysis-pagination"><button disabled={page === 0} onclick={() => page--}>Previous</button><span>Page {page + 1} of {Math.max(1,Math.ceil(report.rows.length/12))}</span><button disabled={(page+1)*12 >= report.rows.length} onclick={() => page++}>Next</button></div>
  <details class="analysis-rules"><summary>Assessment definitions and limits</summary><ul><li>The selected period chooses baseline completion dates; subsequent results are followed through the snapshot. Unfinished baselines use their start date.</li><li>{report.priorPractice} baselines have earlier tracked practice. A baseline means a starting measurement from that date, not necessarily a new language learner.</li><li>Two original forms use the same six everyday listening and reading task types. They alternate by checkpoint. Memory, outside study, self-selection and differences between forms can affect scores. The forms need learner trials and expert review before making a proficiency claim.</li><li>Skipped questions score zero. If audio fails, the learner can retry or return later; the UI does not submit an audio failure as an incorrect response. These self-administered checks are not proctored exams.</li><li>Optional checks are separate from practice visit and lesson-completion rates. No recordings or answer text are stored; only section totals, skipped count, protocol, form and dates.</li></ul><a href="https://www.coe.int/en/web/common-european-framework-reference-languages/assessment" target="_blank" rel="noreferrer">Council of Europe assessment guidance</a></details>
</div>
